import assert from "node:assert/strict";
import { createHash } from "node:crypto";
import { execFileSync } from "node:child_process";
import {
  chmod,
  mkdir,
  readFile,
  realpath,
  rm,
  symlink,
  writeFile,
} from "node:fs/promises";
import path from "node:path";
import { test } from "node:test";
import { fileURLToPath } from "node:url";
import { Client } from "@modelcontextprotocol/client";
import { StdioClientTransport } from "@modelcontextprotocol/client/stdio";
import { createPlan, validate } from "../src/engine.js";
import { goScopeComplete } from "../src/go-scope.js";
import { projectPlan, projectReport } from "../src/output.js";
import { validatedReport } from "../src/report-validation.js";
import { planSchema, reportSummarySchema } from "../src/schemas.js";
import { fixture } from "./helpers.js";
import {
  nativeGoWorkspace,
  workspaceFiles,
  workspaceOptions,
  workspaceConfiguration,
  fixedPolicy,
  hostTarget,
  foreignTarget,
} from "./go-workspace-fixture.js";

const native = {
  skip: nativeGoWorkspace ? false : "Go unavailable",
  timeout: 120000,
};
const hash = (text: string) => createHash("sha256").update(text).digest("hex");
const engineRoot = fileURLToPath(new URL("../../", import.meta.url));
const cli = fileURLToPath(new URL("../src/cli.js", import.meta.url));
const tick = () => new Promise((resolve) => setTimeout(resolve, 25));
async function waitFile(file: string) {
  const deadline = Date.now() + 30000;
  while (Date.now() < deadline) {
    try {
      return await readFile(file, "utf8");
    } catch (error) {
      if ((error as NodeJS.ErrnoException).code !== "ENOENT") throw error;
    }
    await tick();
  }
  throw Error("Original native path never reached its marker");
}

test("go-extensions broken acceptance", native, async (t) => {
  const root = await fixture(t, workspaceFiles(true));
  const { plan } = await createPlan(root);
  planSchema.parse(plan);
  assert.equal(plan.checks.length, 4);
  assert.ok(
    plan.checks.every((check) => check.goWorkspace?.modules.length === 3),
  );
  const broken = await validate(root, workspaceOptions);
  assert.equal(broken.outcome, "failed");
  const app = broken.checks.find(
    (check) => check.project === "app" && check.id === "go.test",
  )!;
  assert.equal(app.status, "failed");
  assert.ok(app.tests && app.tests.failed > 0 && app.tests.passed >= 2);
  assert.match(
    app.processes.at(-1)!.stdout,
    /value=scopeToken got=true want=false/,
  );
  assert.equal(broken.sourceChanged, false);
  assert.equal(
    app.goWorkspace?.sha256,
    hash(await readFile(path.join(root, "go.work"), "utf8")),
  );
  await writeFile(
    path.join(root, "policy unit/generated.go"),
    '// Code generated by an original synthetic fixture; DO NOT EDIT.\npackage policy\nconst GeneratedValue int = "wrong"\n',
  );
  const generated = await validate(root, workspaceOptions);
  const failure = generated.checks.find(
    (check) => check.project === "policy unit" && check.id === "go.build",
  )!;
  assert.equal(failure.status, "failed");
  assert.equal(failure.findingsComplete, true);
  assert.ok(
    failure.findings?.some(
      (f) => f.file === "policy unit/generated.go" && f.line === 3,
    ),
  );
});

test("go-extensions fixed acceptance", native, async (t) => {
  const root = await fixture(t, workspaceFiles(true));
  await writeFile(path.join(root, "policy unit/value.go"), fixedPolicy);
  const fixed = await validate(root, workspaceOptions);
  assert.equal(fixed.outcome, "passed");
  assert.equal(fixed.checks.length, 4);
  assert.ok(
    fixed.checks.every(
      (check) => check.status === "passed" && check.goWorkspace,
    ),
  );
  assert.equal(
    fixed.checks.find(
      (check) => check.project === "app" && check.id === "go.test",
    )!.tests?.failed,
    0,
  );
  assert.equal(fixed.sourceChanged, false);
  for (const module of fixed.checks[0]!.goWorkspace!.modules) {
    assert.equal(
      module.manifestDigest,
      hash(await readFile(path.join(root, module.directory, "go.mod"), "utf8")),
    );
  }
  validatedReport(fixed);
  const { plan } = await createPlan(root);
  const build = plan.checks.find(
    (check) => check.project === "policy unit" && check.id === "go.build",
  )!;
  assert.ok(build.scope.includes("generated.go"));
  assert.ok(build.commands.at(-1)?.temporaryDirectory);
});

test("go-extensions near-miss acceptance", native, async (t) => {
  const files = workspaceFiles();
  files["policy unit/go.mod"] +=
    'replace example.invalid/helper => "../helper unit"\n';
  files["go.work"] =
    'go 1.23\n// replace evil.invalid/ghost => /outside\nuse (\n ./app\n "./policy unit"\n)\n';
  files["checktrail.json"] = workspaceConfiguration([
    "go.build",
    "go.test",
    "go.test-race",
    "go.staticcheck",
    "go.golangci-lint",
  ]);
  for (const project of ["app", "policy unit"]) {
    files[project + "/.golangci.yml"] =
      'version: "2"\nlinters:\n  default: none\n  enable: [govet, staticcheck, unused]\n';
    files[project + "/ordinary.go"] =
      "//go:build ordinary\n\npackage " +
      (project === "app" ? "app" : "policy") +
      '\nconst SelectedTag = "ordinary"\n';
    files[project + "/race_selected.go"] =
      "//go:build race\n\npackage " +
      (project === "app" ? "app" : "policy") +
      "\nconst RaceTag = true\n";
    files[project + "/checktrail.go-build.json"] = JSON.stringify({
      schemaVersion: 2,
      profiles: [
        {
          name: "ordinary",
          tags: ["ordinary"],
          checks: ["go.build", "go.test", "go.staticcheck", "go.golangci-lint"],
          repetitions: 1,
          target: hostTarget,
          excludedFiles: [
            {
              path: "race_selected.go",
              reason: "Covered by the native race profile",
            },
          ],
        },
        {
          name: "race",
          tags: ["ordinary"],
          checks: ["go.test-race"],
          repetitions: 1,
          target: { ...hostTarget, cgo: true },
          excludedFiles: [],
        },
        {
          name: "foreign",
          tags: ["ordinary"],
          checks: ["go.build", "go.test"],
          repetitions: 1,
          target: foreignTarget,
          excludedFiles: [
            { path: "race_selected.go", reason: "Race is host-only" },
          ],
        },
      ],
    });
  }
  for (const [file, content] of Object.entries(files)) {
    if (file.endsWith("/value.go")) {
      const packageName = file.startsWith("app/")
        ? "app"
        : file.startsWith("policy unit/")
          ? "policy"
          : "helper";
      files[file] =
        "// Package " +
        packageName +
        " exercises an original workspace control.\n" +
        content.replace(
          "func Allowed",
          "// Allowed enforces the original declared boundary.\nfunc Allowed",
        );
    }
  }
  files["policy unit/generated.go"] = files[
    "policy unit/generated.go"
  ]!.replace("EDIT.\npackage", "EDIT.\n\npackage");
  const root = await fixture(t, files);
  const report = await validate(root, workspaceOptions);
  assert.equal(
    report.outcome,
    "incomplete",
    JSON.stringify(
      report.checks
        .filter((c) => c.status !== "passed")
        .map((c) => ({
          id: c.id,
          project: c.project,
          status: c.status,
          reason: c.reason,
          errors: c.processes.slice(-1).map((p) => ({
            err: p.stderr,
            out: p.stdout.slice(-1000),
          })),
        })),
    ),
  );
  assert.equal(report.checks.length, 14);
  const unavailable = report.checks.filter(
    (check) => check.status !== "passed",
  );
  assert.equal(
    unavailable.length,
    2,
    JSON.stringify(
      unavailable.map((check) => ({
        id: check.id,
        status: check.status,
        reason: check.reason,
      })),
    ),
  );
  assert.ok(
    unavailable.every(
      (check) =>
        check.id === "go.test" &&
        check.status === "unavailable" &&
        check.goBuild?.profile === "foreign",
    ),
  );
  assert.ok(
    report.checks
      .filter(
        (check) =>
          check.goBuild?.profile === "foreign" && check.id === "go.build",
      )
      .every(
        (check) =>
          check.status === "passed" && check.goTarget?.os === foreignTarget.os,
      ),
  );
  for (const check of report.checks.filter(
    (check) => check.id === "go.test-race",
  )) {
    assert.equal(check.status, "passed");
    assert.equal(check.goTarget?.cgo, true);
    const packages = check.processes.find(
      (process) => process.command.args[0] === "list",
    )!.stdout;
    assert.match(packages, /race_selected.go/);
    assert.match(packages, /ordinary.go/);
  }
  validatedReport(report);
  const ordinary = report.checks.find(
    (check) => check.goBuild?.profile === "ordinary",
  )!;
  const forged = structuredClone(report);
  forged.checks.find(
    (check) => check.executionId === ordinary.executionId,
  )!.goWorkspace!.modules[0]!.module = "example.invalid/foreign";
  assert.throws(() => validatedReport(forged), /execution identity/);
});

test("go-extensions prerequisite acceptance", async (t) => {
  const root = await fixture(t, workspaceFiles());
  const valid = await readFile(path.join(root, "go.work"), "utf8");
  for (const text of [
    "go 1.23\nuse ../outside\n",
    "go 1.23\nuse /outside\n",
    "go 1.23\nuse (\n ./app\n ./app\n)\n",
    "go 1.23\nuse ./missing\n",
    'go 1.23\nuse (\n ./app\n "./policy unit"\n)\nreplace example.invalid/helper => /outside\n',
    'go 1.23\nuse (\n ./app\n "./policy unit"\n)\nunknown setting\n',
    "go 1.23\nuse (\n ./app\n",
    "go 1.23\nuse `./app`\n",
  ]) {
    await writeFile(path.join(root, "go.work"), text);
    const { plan } = await createPlan(root);
    assert.ok(plan.checks.every((check) => check.unavailableReason));
    const report = await validate(root, workspaceOptions);
    assert.equal(report.outcome, "incomplete");
    assert.ok(
      report.checks.every(
        (check) =>
          check.status === "unavailable" && check.processes.length === 0,
      ),
    );
  }
  await writeFile(path.join(root, "go.work"), valid);
  await rm(path.join(root, "helper unit/go.mod"));
  assert.ok(
    (await createPlan(root)).plan.checks.every(
      (check) => check.unavailableReason,
    ),
  );
  await writeFile(
    path.join(root, "helper unit/go.mod"),
    "module example.invalid/helper\ngo 1.23\n",
  );
  await symlink(path.join(root, "go.work"), path.join(root, "app/go.work"));
  assert.ok(
    (await createPlan(root)).plan.checks
      .filter((check) => check.project === "app")
      .every((check) => check.unavailableReason),
  );
  await rm(path.join(root, "app/go.work"));
  await mkdir(path.join(root, "tools"));
  await writeFile(
    path.join(root, "tools/go"),
    "#!/bin/sh\n: > executed\nexit 99\n",
  );
  await chmod(path.join(root, "tools/go"), 0o755);
  await writeFile(
    path.join(root, "checktrail.json"),
    workspaceConfiguration(["go.test"], ["PATH"]),
  );
  await createPlan(root, { environment: { PATH: path.join(root, "tools") } });
  await assert.rejects(readFile(path.join(root, "app/executed")), {
    code: "ENOENT",
  });
  await rm(path.join(root, "tools/go"));
  const absent = await validate(root, {
    ...workspaceOptions,
    environment: { PATH: path.join(root, "tools") },
  });
  assert.equal(absent.outcome, "incomplete");
  assert.ok(absent.checks.every((check) => check.status !== "passed"));
  const extra = Array.from({ length: 14 }, (_, index) => "extra" + index);
  for (const directory of extra) {
    await mkdir(path.join(root, directory));
    await writeFile(
      path.join(root, directory, "go.mod"),
      "module example.invalid/" + directory + "\ngo 1.23\n",
    );
  }
  await writeFile(path.join(root, "checktrail.json"), workspaceConfiguration());
  const bounded = (count: number) =>
    'go 1.23\nuse (\n ./app\n "./policy unit"\n' +
    extra
      .slice(0, count)
      .map((value) => " ./" + value + "\n")
      .join("") +
    ')\nreplace example.invalid/helper => "./helper unit"\n';
  await writeFile(path.join(root, "go.work"), bounded(13));
  assert.ok(
    (await createPlan(root)).plan.checks.every(
      (check) =>
        check.goWorkspace?.modules.length === 16 && !check.unavailableReason,
    ),
  );
  await writeFile(path.join(root, "go.work"), bounded(14));
  assert.ok(
    (await createPlan(root)).plan.checks.every((check) =>
      check.unavailableReason?.includes("sixteen"),
    ),
  );
});

test("go-extensions stale acceptance", native, async (t) => {
  const files = workspaceFiles();
  files["checktrail.json"] = JSON.stringify({
    schemaVersion: 1,
    projects: [{ path: "app", checks: ["go.test"], environment: [] }],
  });
  files["app/mutation_test.go"] =
    'package app\nimport "testing"\nimport "os"\nfunc TestWorkspaceMutation(t *testing.T){file,err:=os.OpenFile("../go.work",os.O_APPEND|os.O_WRONLY,0600);if err!=nil{t.Fatal(err)};defer file.Close();if _,err=file.WriteString("// changed during original native validation\\n");err!=nil{t.Fatal(err)}}\n';
  const root = await fixture(t, files);
  const report = await validate(root, workspaceOptions);
  assert.equal(report.checks[0]!.status, "passed");
  assert.equal(report.sourceChanged, true);
  assert.equal(report.outcome, "incomplete");
  assert.notEqual(
    report.checks[0]!.goWorkspace!.sha256,
    hash(await readFile(path.join(root, "go.work"), "utf8")),
  );
  const forged = { ...report, sourceChanged: false, outcome: "passed" };
  assert.throws(() => validatedReport(forged), /contradicts|fingerprint/);
  const before = (await createPlan(root)).plan;
  await writeFile(
    path.join(root, "helper unit/value.go"),
    "package helper\nconst Enabled = false\n",
  );
  const after = (await createPlan(root)).plan;
  assert.notEqual(before.sourceFingerprint, after.sourceFingerprint);
});

test("go-extensions empty acceptance", async (t) => {
  const root = await realpath(await fixture(t, workspaceFiles()));
  const check = (await createPlan(root)).plan.checks.find(
    (check) => check.id === "go.build" && check.project === "app",
  )!;
  const pkg = {
    Dir: path.join(root, "app"),
    ImportPath: "example.invalid/app",
    GoFiles: ["value.go"],
    TestGoFiles: ["value_test.go"],
    Module: {
      Path: "example.invalid/app",
      Main: true,
      Dir: path.join(root, "app"),
      GoMod: path.join(root, "app/go.mod"),
    },
  };
  const result = {
    command: check.commands[0]!,
    exitCode: 0,
    signal: null,
    stdout: JSON.stringify(pkg),
    stderr: "",
    durationMs: 1,
    timedOut: false,
    cancelled: false,
    truncated: false,
  };
  assert.equal(goScopeComplete(check, result, root), true);
  for (const changes of [
    { stdout: "" },
    { stdout: "{}" },
    { stdout: result.stdout.slice(0, -1) },
    { stdout: JSON.stringify({ ...pkg, GoFiles: [] }) },
    { stdout: JSON.stringify({ ...pkg, Module: undefined }) },
    {
      stdout: JSON.stringify({
        ...pkg,
        Module: { ...pkg.Module, Main: false },
      }),
    },
    {
      stdout: JSON.stringify({
        ...pkg,
        Module: { ...pkg.Module, Path: "example.invalid/foreign" },
      }),
    },
    {
      stdout: JSON.stringify({
        ...pkg,
        Module: { ...pkg.Module, GoMod: path.join(root, "helper unit/go.mod") },
      }),
    },
    {
      command: {
        ...result.command,
        env: { ...result.command.env, GOWORK: "off" },
      },
    },
    { cancelled: true },
    { timedOut: true },
    { truncated: true },
  ]) {
    assert.equal(
      goScopeComplete(check, { ...result, ...changes }, root),
      false,
      JSON.stringify(changes),
    );
  }
  if (nativeGoWorkspace) {
    await rm(path.join(root, "app/value.go"));
    await rm(path.join(root, "app/value_test.go"));
    await writeFile(
      path.join(root, "checktrail.json"),
      JSON.stringify({
        schemaVersion: 1,
        projects: [{ path: "app", checks: ["go.build"] }],
      }),
    );
    const empty = await validate(root, workspaceOptions);
    assert.equal(empty.outcome, "incomplete");
    assert.notEqual(empty.checks[0]!.status, "passed");
  }
});

test("go-extensions privacy acceptance", native, async (t) => {
  const root = await fixture(t, workspaceFiles());
  const plan = (await createPlan(root)).plan;
  const summary = projectPlan(plan, false);
  assert.ok(
    !JSON.stringify(summary).includes("policy unit") &&
      !JSON.stringify(summary).includes(root),
  );
  await assert.rejects(validate(root, { trusted: false }), /operator trust/);
  const library = await validate(root, workspaceOptions);
  const projection = projectReport(library, false);
  reportSummarySchema.parse(projection);
  assert.ok(
    !JSON.stringify(projection).includes("example.invalid") &&
      !JSON.stringify(projection).includes(root),
  );
  const command = JSON.parse(
    execFileSync(
      process.execPath,
      [cli, "run", "--root", root, "--trust-project", "--timeout-ms", "120000"],
      { encoding: "utf8" },
    ),
  );
  assert.equal(command.outcome, "passed");
  assert.deepEqual(command.checks, projection.checks);
  for (const trusted of [false, true]) {
    const client = new Client(
      { name: "original-go-workspace", version: "1" },
      { versionNegotiation: { mode: { pin: "2026-07-28" } } },
    );
    try {
      await client.connect(
        new StdioClientTransport({
          command: process.execPath,
          args: [
            cli,
            "serve",
            "--root",
            root,
            ...(trusted ? ["--allow-execution"] : []),
          ],
          stderr: "pipe",
        }),
      );
      const rejected = await client.callTool({
        name: "validation_run",
        arguments: { trusted: true },
      });
      assert.equal(rejected.isError, true);
      const planned = await client.callTool({
        name: "validation_plan",
        arguments: {},
      });
      assert.deepEqual(planned.structuredContent, summary);
      const received = await client.callTool({
        name: "validation_run",
        arguments: {},
      });
      if (!trusted) assert.equal(received.isError, true);
      else {
        assert.notEqual(received.isError, true);
        const report = received.structuredContent as {
          outcome: string;
          checks: unknown;
        };
        assert.equal(report.outcome, "passed");
        assert.deepEqual(report.checks, projection.checks);
      }
    } finally {
      await client.close();
    }
  }
});

test(
  "go-extensions lifecycle acceptance",
  { ...native, skip: native.skip || process.platform === "win32" },
  async (t) => {
    const files = workspaceFiles();
    files["checktrail.json"] = JSON.stringify({
      schemaVersion: 1,
      projects: [
        {
          path: "app",
          checks: ["go.test"],
          environment: ["ORIGINAL_WORKSPACE_MODE"],
        },
      ],
    });
    files["app/lifecycle_test.go"] =
      'package app\nimport "testing"\nimport "os"\nimport "os/exec"\nimport "syscall"\nimport "strconv"\nimport "fmt"\nimport "strings"\nimport "time"\nfunc TestLifecycle(t *testing.T){mode:=os.Getenv("ORIGINAL_WORKSPACE_MODE");if mode=="warm"{return}; if mode=="flood"{fmt.Print(strings.Repeat("x",2*1024*1024));return};cmd:=exec.Command("sleep","60");cmd.SysProcAttr=&syscall.SysProcAttr{Setpgid:true};if err:=cmd.Start();err!=nil{t.Fatal(err)};go cmd.Wait();if err:=os.WriteFile(".checktrail/pid",[]byte(strconv.Itoa(cmd.Process.Pid)),0600);err!=nil{t.Fatal(err)};for{time.Sleep(time.Second)}}\n';
    const root = await fixture(t, files);
    await mkdir(path.join(root, "app/.checktrail"));
    const environment = (mode: string) => ({ ORIGINAL_WORKSPACE_MODE: mode });
    const warm = await validate(root, {
      ...workspaceOptions,
      environment: environment("warm"),
    });
    assert.equal(warm.outcome, "passed");
    const marker = path.join(root, "app/.checktrail/pid");
    for (const mode of ["cancel", "timeout"]) {
      const controller = new AbortController();
      let pid: number | undefined;
      try {
        const pending = validate(root, {
          ...workspaceOptions,
          timeoutMs: mode === "timeout" ? 5000 : 120000,
          signal: controller.signal,
          environment: environment(mode),
        });
        pid = Number(await waitFile(marker));
        assert.ok(Number.isInteger(pid) && pid > 1);
        if (mode === "cancel") controller.abort();
        const report = await pending;
        assert.equal(report.outcome, "incomplete");
        assert.notEqual(report.checks[0]!.status, "passed");
        assert.ok(
          report.checks[0]!.processes.some((result) =>
            mode === "cancel" ? result.cancelled : result.timedOut,
          ),
        );
        const deadline = Date.now() + 5000;
        let alive = true;
        while (Date.now() < deadline) {
          try {
            process.kill(pid, 0);
          } catch {
            alive = false;
            break;
          }
          await tick();
        }
        assert.equal(
          alive,
          false,
          "Reached detached native descendant survived cleanup",
        );
      } finally {
        controller.abort();
        if (pid) {
          try {
            process.kill(pid, "SIGKILL");
          } catch {
            /* already removed */
          }
        }
        await rm(marker, { force: true });
      }
    }
    const flood = await validate(root, {
      ...workspaceOptions,
      environment: environment("flood"),
    });
    assert.equal(flood.outcome, "incomplete");
    assert.ok(flood.checks[0]!.processes.some((result) => result.truncated));
    const controller = new AbortController();
    controller.abort();
    const cancelled = await validate(root, {
      ...workspaceOptions,
      signal: controller.signal,
      environment: environment("warm"),
    });
    assert.equal(cancelled.outcome, "incomplete");
    assert.equal(cancelled.checks[0]!.processes.length, 0);
  },
);

test("go-extensions installed acceptance", native, async (t) => {
  if (process.env.CHECKTRAIL_GATE_GO_INSTALLED === "1") {
    const actual = await realpath(
      fileURLToPath(new URL("../src/engine.js", import.meta.url)),
    );
    assert.ok(
      actual.includes(
        path.join("node_modules", "@stsepelin", "checktrail", "dist", "src"),
      ),
    );
    const root = await fixture(t, workspaceFiles(true));
    assert.equal((await validate(root, workspaceOptions)).outcome, "failed");
    await writeFile(path.join(root, "policy unit/value.go"), fixedPolicy);
    assert.equal((await validate(root, workspaceOptions)).outcome, "passed");
  } else {
    const receipt = JSON.parse(
      execFileSync(
        process.execPath,
        [path.join(engineRoot, "scripts/verify-go-workspace-package.mjs")],
        {
          encoding: "utf8",
          maxBuffer: 1024 * 1024,
          timeout: 120000,
          env: Object.fromEntries(
            Object.entries(process.env).filter(
              ([name]) => name !== "NODE_TEST_CONTEXT",
            ),
          ),
        },
      ),
    );
    assert.equal(receipt.offlineProductionInstall, true);
    assert.equal(receipt.profile.complete, true);
    assert.equal(receipt.profile.passed, 9);
    assert.equal(receipt.lifecycleScriptsExecuted, false);
  }
});
