import { spawnSync } from "node:child_process";

export const goHost = (() => {
  const result = spawnSync("go", ["env", "-json", "GOHOSTOS", "GOHOSTARCH"], {
    encoding: "utf8",
  });
  return result.status === 0
    ? (JSON.parse(result.stdout) as { GOHOSTOS: string; GOHOSTARCH: string })
    : null;
})();
export const nativeGoWorkspace = goHost !== null;
export const hostTarget = {
  os: goHost?.GOHOSTOS ?? "linux",
  arch: goHost?.GOHOSTARCH ?? "arm64",
  cgo: false,
};
export const foreignTarget = {
  ...hostTarget,
  os: hostTarget.os === "windows" ? "linux" : "windows",
};
export const workspaceOptions = { trusted: true, timeoutMs: 120000 };
export const brokenPolicy =
  'package policy\nimport "strings"\nimport "example.invalid/helper"\nfunc Allowed(value string) bool { return helper.Enabled && strings.HasPrefix(value,"scope") }\n';
export const fixedPolicy =
  'package policy\nimport "strings"\nimport "example.invalid/helper"\nfunc Allowed(value string) bool { return helper.Enabled && (value=="scope" || strings.HasPrefix(value,"scope:")) }\n';
export const workspaceConfiguration = (
  checks: string[] = ["go.build", "go.test"],
  environment: string[] = [],
) =>
  JSON.stringify({
    schemaVersion: 1,
    projects: [
      { path: "app", checks, environment },
      { path: "policy unit", checks, environment },
    ],
  });
export function workspaceFiles(broken = false): Record<string, string> {
  return {
    "go.work":
      'go 1.23\nuse (\n ./app\n "./policy unit" // an original quoted member\n)\nreplace example.invalid/helper => "./helper unit"\n',
    "app/go.mod": "module example.invalid/app\ngo 1.23\n",
    "app/value.go":
      'package app\nimport "example.invalid/policy"\nfunc Allowed(value string) bool { return policy.Allowed(value) }\n',
    "app/value_test.go":
      'package app\nimport "testing"\nfunc TestAllowed(t *testing.T) { cases:=[]struct{value string;want bool}{{"scope:read",true},{"scopeToken",false},{"other",false}};for _,c:=range cases {t.Run(c.value,func(t *testing.T){if got:=Allowed(c.value);got!=c.want{t.Fatalf("value=%s got=%t want=%t",c.value,got,c.want)}})} }\n',
    "policy unit/go.mod":
      "module example.invalid/policy\ngo 1.23\nrequire example.invalid/helper v0.0.0\n",
    "policy unit/value.go": broken ? brokenPolicy : fixedPolicy,
    "policy unit/generated.go":
      "// Code generated by an original synthetic fixture; DO NOT EDIT.\npackage policy\nconst GeneratedValue int = 7\n",
    "policy unit/value_test.go":
      'package policy\nimport "testing"\nfunc TestGenerated(t *testing.T){if GeneratedValue!=7{t.Fatal(GeneratedValue)}}\n',
    "helper unit/go.mod": "module example.invalid/helper\ngo 1.23\n",
    "helper unit/value.go": "package helper\nconst Enabled = true\n",
    "checktrail.json": workspaceConfiguration(),
  };
}
