import { spawnSync } from "node:child_process";
import type { TestContext } from "node:test";
import type { z } from "zod";
import type { fastapiConfigSchema } from "../src/fastapi.js";
import { validate } from "../src/engine.js";
import { fixture } from "./helpers.js";
export const available =
  spawnSync(
    "python3",
    [
      "-I",
      "-c",
      "import sys;from importlib.metadata import version;assert sys.version_info[:3]==(3,12,13);assert [version(n) for n in ['fastapi','starlette','pydantic']]==['0.141.1','1.6.0','2.13.5']",
    ],
    { timeout: 10000 },
  ).status === 0;
export const source =
  "from contextlib import asynccontextmanager\nfrom fastapi import FastAPI, APIRouter, Depends, Security, WebSocket\nfrom fastapi.security import OAuth2PasswordBearer, SecurityScopes\nfrom starlette.requests import Request\nfrom starlette.routing import Host\nfrom starlette.responses import JSONResponse\nfrom pydantic import BaseModel\ntrace=[]\ncalls=[]\nasync def original_settings(): return 'unconfigured'\nasync def configured_settings(): return 'native-settings'\n@asynccontextmanager\nasync def root_life(app):\n    trace.append('root.enter')\n    try: yield {'original_lifespan':True}\n    finally:\n        trace.append('root.exit')\n        import pathlib,json\n        pathlib.Path('.checktrail').mkdir(exist_ok=True)\n        pathlib.Path('.checktrail/lifespan.closed').write_text(json.dumps(trace))\n@asynccontextmanager\nasync def included_life(app):\n    trace.append('included.enter')\n    try: yield\n    finally: trace.append('included.exit')\nclass Initialize:\n    def __init__(self,app,label='init'):self.app=app;self.label=label\n    async def __call__(self,scope,receive,send):\n        if scope['type'] in ('http','websocket'):\n            scope.setdefault('state',{})['ready']=True\n        await self.app(scope,receive,send)\nclass Authorize:\n    def __init__(self,app):self.app=app\n    async def __call__(self,scope,receive,send):\n        if scope['type']=='http' and not scope.get('state',{}).get('ready'):\n            await JSONResponse({'detail':'initialization required'},status_code=403)(scope,receive,send);return\n        await self.app(scope,receive,send)\nclass Item(BaseModel):\n    id:int\n    enabled:bool=True\nbearer=OAuth2PasswordBearer(tokenUrl='/token',scopes={'catalog:read':'Read catalog','catalog:write':'Write catalog'},auto_error=False)\nasync def token(security_scopes:SecurityScopes,token:str|None=Depends(bearer)):\n    return {'scopes':security_scopes.scopes,'token':token}\nasync def before():\n    calls.append('before')\n    return 'before'\nasync def combined(access=Security(token,scopes=['catalog:read'])):return access\nasync def socket_dependency():return 'socket-ready'\nrouter=APIRouter(prefix='/catalog',dependencies=[Depends(before)],lifespan=included_life)\n@router.get('/items',response_model=list[Item])\nasync def items(request:Request,access=Security(combined,scopes=['catalog:write']),settings=Depends(original_settings)):\n    assert request.state.original_lifespan and request.state.ready\n    assert access == {'scopes':['catalog:write','catalog:read'],'token':'original'}\n    assert settings == 'native-settings' and calls == ['before']\n    return [{'id':'1'},{'id':'2'}]\n@router.websocket('/socket')\nasync def socket(websocket:WebSocket,ready=Depends(socket_dependency)):\n    await websocket.accept();await websocket.send_json({'ready':ready});await websocket.close()\napp=FastAPI(lifespan=root_life)\napp.dependency_overrides[original_settings]=configured_settings\napp.include_router(router,prefix='/v1',dependencies=[Depends(before)])\napp.add_middleware(Authorize)\napp.add_middleware(Initialize,label='root')\n@app.get('/state')\nasync def state():return trace\nchild=FastAPI(openapi_url=None)\n@child.get('/items',response_model=Item)\nasync def mounted():return {'id':'3'}\nchild.add_middleware(Initialize,label='child')\napp.mount('/mounted',child,name='mounted')\nhosted=FastAPI(openapi_url=None)\n@hosted.get('/items')\nasync def host():return {'host':True}\napp.router.routes.insert(0,Host('api.example.test',app=hosted,name='hosted'))\n";
/** Fixed synthetic operator contract; expectations change only through an explicit fixture edit. */
export const profile: Extract<
  z.infer<typeof fastapiConfigSchema>,
  { schemaVersion: 2 }
> = {
  schemaVersion: 2,
  module: "app",
  attribute: "app",
  assembly: "original.fastapi.assembly",
  environment: "test",
  expectedRoutes: [
    {
      scope: '[{"host":"api.example.test","kind":"host","name":"hosted"}]',
      ordinal: "0.0",
      protocol: "http",
      method: "GET",
      path: "/items",
      handler: "app.host",
      name: "host",
      dependencies: [],
      responseModel: null,
      responseClass: "starlette.responses.JSONResponse",
      responseOptions:
        '{"exclude":["null"],"include":["null"],"response_model_by_alias":true,"response_model_exclude_defaults":false,"response_model_exclude_none":false,"response_model_exclude_unset":false}',
      statusCode: null,
      includeInSchema: true,
      application: true,
    },
    {
      scope: "[]",
      ordinal: "1",
      protocol: "http",
      method: "GET",
      path: "/openapi.json",
      handler: "fastapi.applications.FastAPI.setup.<locals>.openapi",
      name: "openapi",
      dependencies: [],
      responseModel: null,
      responseClass: null,
      responseOptions:
        '{"exclude":["null"],"include":["null"],"response_model_by_alias":null,"response_model_exclude_defaults":null,"response_model_exclude_none":null,"response_model_exclude_unset":null}',
      statusCode: null,
      includeInSchema: false,
      application: false,
    },
    {
      scope: "[]",
      ordinal: "1",
      protocol: "http",
      method: "HEAD",
      path: "/openapi.json",
      handler: "fastapi.applications.FastAPI.setup.<locals>.openapi",
      name: "openapi",
      dependencies: [],
      responseModel: null,
      responseClass: null,
      responseOptions:
        '{"exclude":["null"],"include":["null"],"response_model_by_alias":null,"response_model_exclude_defaults":null,"response_model_exclude_none":null,"response_model_exclude_unset":null}',
      statusCode: null,
      includeInSchema: false,
      application: false,
    },
    {
      scope: "[]",
      ordinal: "2",
      protocol: "http",
      method: "GET",
      path: "/docs",
      handler: "fastapi.applications.FastAPI.setup.<locals>.swagger_ui_html",
      name: "swagger_ui_html",
      dependencies: [],
      responseModel: null,
      responseClass: null,
      responseOptions:
        '{"exclude":["null"],"include":["null"],"response_model_by_alias":null,"response_model_exclude_defaults":null,"response_model_exclude_none":null,"response_model_exclude_unset":null}',
      statusCode: null,
      includeInSchema: false,
      application: false,
    },
    {
      scope: "[]",
      ordinal: "2",
      protocol: "http",
      method: "HEAD",
      path: "/docs",
      handler: "fastapi.applications.FastAPI.setup.<locals>.swagger_ui_html",
      name: "swagger_ui_html",
      dependencies: [],
      responseModel: null,
      responseClass: null,
      responseOptions:
        '{"exclude":["null"],"include":["null"],"response_model_by_alias":null,"response_model_exclude_defaults":null,"response_model_exclude_none":null,"response_model_exclude_unset":null}',
      statusCode: null,
      includeInSchema: false,
      application: false,
    },
    {
      scope: "[]",
      ordinal: "3",
      protocol: "http",
      method: "GET",
      path: "/docs/oauth2-redirect",
      handler:
        "fastapi.applications.FastAPI.setup.<locals>.swagger_ui_redirect",
      name: "swagger_ui_redirect",
      dependencies: [],
      responseModel: null,
      responseClass: null,
      responseOptions:
        '{"exclude":["null"],"include":["null"],"response_model_by_alias":null,"response_model_exclude_defaults":null,"response_model_exclude_none":null,"response_model_exclude_unset":null}',
      statusCode: null,
      includeInSchema: false,
      application: false,
    },
    {
      scope: "[]",
      ordinal: "3",
      protocol: "http",
      method: "HEAD",
      path: "/docs/oauth2-redirect",
      handler:
        "fastapi.applications.FastAPI.setup.<locals>.swagger_ui_redirect",
      name: "swagger_ui_redirect",
      dependencies: [],
      responseModel: null,
      responseClass: null,
      responseOptions:
        '{"exclude":["null"],"include":["null"],"response_model_by_alias":null,"response_model_exclude_defaults":null,"response_model_exclude_none":null,"response_model_exclude_unset":null}',
      statusCode: null,
      includeInSchema: false,
      application: false,
    },
    {
      scope: "[]",
      ordinal: "4",
      protocol: "http",
      method: "GET",
      path: "/redoc",
      handler: "fastapi.applications.FastAPI.setup.<locals>.redoc_html",
      name: "redoc_html",
      dependencies: [],
      responseModel: null,
      responseClass: null,
      responseOptions:
        '{"exclude":["null"],"include":["null"],"response_model_by_alias":null,"response_model_exclude_defaults":null,"response_model_exclude_none":null,"response_model_exclude_unset":null}',
      statusCode: null,
      includeInSchema: false,
      application: false,
    },
    {
      scope: "[]",
      ordinal: "4",
      protocol: "http",
      method: "HEAD",
      path: "/redoc",
      handler: "fastapi.applications.FastAPI.setup.<locals>.redoc_html",
      name: "redoc_html",
      dependencies: [],
      responseModel: null,
      responseClass: null,
      responseOptions:
        '{"exclude":["null"],"include":["null"],"response_model_by_alias":null,"response_model_exclude_defaults":null,"response_model_exclude_none":null,"response_model_exclude_unset":null}',
      statusCode: null,
      includeInSchema: false,
      application: false,
    },
    {
      scope: "[]",
      ordinal: "5",
      protocol: "http",
      method: "GET",
      path: "/v1/catalog/items",
      handler: "app.items",
      name: "items",
      dependencies: [
        '{"call":"app.before","effectiveScopes":[],"kind":"function","order":[0],"ownScopes":[],"parentScopes":[],"scope":null,"security":null,"useCache":true}',
        '{"call":"app.before","effectiveScopes":[],"kind":"function","order":[1],"ownScopes":[],"parentScopes":[],"scope":null,"security":null,"useCache":true}',
        '{"call":"app.combined","effectiveScopes":["catalog:write"],"kind":"function","order":[2],"ownScopes":["catalog:write"],"parentScopes":[],"scope":null,"security":null,"useCache":true}',
        '{"call":"app.token","effectiveScopes":["catalog:write","catalog:read"],"kind":"function","order":[2,0],"ownScopes":["catalog:read"],"parentScopes":["catalog:write"],"scope":null,"security":null,"useCache":true}',
        '{"call":"fastapi.security.oauth2.OAuth2PasswordBearer","effectiveScopes":["catalog:write","catalog:read"],"kind":"instance","order":[2,0,0],"ownScopes":[],"parentScopes":["catalog:write","catalog:read"],"scope":null,"security":{"autoError":false,"model":{"flows":{"password":{"scopes":{"catalog:read":"Read catalog","catalog:write":"Write catalog"},"tokenUrl":"/token"}},"type":"oauth2"},"scheme":"OAuth2PasswordBearer"},"useCache":true}',
        '{"call":"app.original_settings","effectiveScopes":[],"kind":"function","order":[3],"ownScopes":[],"parentScopes":[],"scope":null,"security":null,"useCache":true}',
      ],
      responseModel:
        '{"$defs":{"Item":{"properties":{"enabled":{"default":true,"title":"Enabled","type":"boolean"},"id":{"title":"Id","type":"integer"}},"required":["id"],"title":"Item","type":"object"}},"items":{"$ref":"#/$defs/Item"},"type":"array"}',
      responseClass: "starlette.responses.JSONResponse",
      responseOptions:
        '{"exclude":["null"],"include":["null"],"response_model_by_alias":true,"response_model_exclude_defaults":false,"response_model_exclude_none":false,"response_model_exclude_unset":false}',
      statusCode: null,
      includeInSchema: true,
      application: true,
    },
    {
      scope: "[]",
      ordinal: "6",
      protocol: "websocket",
      method: "WEBSOCKET",
      path: "/v1/catalog/socket",
      handler: "app.socket",
      name: "socket",
      dependencies: [
        '{"call":"app.before","effectiveScopes":[],"kind":"function","order":[0],"ownScopes":[],"parentScopes":[],"scope":null,"security":null,"useCache":true}',
        '{"call":"app.before","effectiveScopes":[],"kind":"function","order":[1],"ownScopes":[],"parentScopes":[],"scope":null,"security":null,"useCache":true}',
        '{"call":"app.socket_dependency","effectiveScopes":[],"kind":"function","order":[2],"ownScopes":[],"parentScopes":[],"scope":null,"security":null,"useCache":true}',
      ],
      responseModel: null,
      responseClass: null,
      responseOptions:
        '{"exclude":["null"],"include":["null"],"response_model_by_alias":null,"response_model_exclude_defaults":null,"response_model_exclude_none":null,"response_model_exclude_unset":null}',
      statusCode: null,
      includeInSchema: false,
      application: true,
    },
    {
      scope: "[]",
      ordinal: "7",
      protocol: "http",
      method: "GET",
      path: "/state",
      handler: "app.state",
      name: "state",
      dependencies: [],
      responseModel: null,
      responseClass: "starlette.responses.JSONResponse",
      responseOptions:
        '{"exclude":["null"],"include":["null"],"response_model_by_alias":true,"response_model_exclude_defaults":false,"response_model_exclude_none":false,"response_model_exclude_unset":false}',
      statusCode: null,
      includeInSchema: true,
      application: true,
    },
    {
      scope: '[{"kind":"mount","name":"mounted","path":"/mounted"}]',
      ordinal: "8.0",
      protocol: "http",
      method: "GET",
      path: "/items",
      handler: "app.mounted",
      name: "mounted",
      dependencies: [],
      responseModel:
        '{"properties":{"enabled":{"default":true,"title":"Enabled","type":"boolean"},"id":{"title":"Id","type":"integer"}},"required":["id"],"title":"Item","type":"object"}',
      responseClass: "starlette.responses.JSONResponse",
      responseOptions:
        '{"exclude":["null"],"include":["null"],"response_model_by_alias":true,"response_model_exclude_defaults":false,"response_model_exclude_none":false,"response_model_exclude_unset":false}',
      statusCode: null,
      includeInSchema: true,
      application: true,
    },
  ],
  expectedMiddleware: [
    {
      scope: "[]",
      position: 0,
      kind: "user",
      name: "app.Initialize",
      arguments: '["tuple",[]]',
      options: '["object",[["label",["string","root"]]]]',
      constructed: false,
    },
    {
      scope: "[]",
      position: 1,
      kind: "user",
      name: "app.Authorize",
      arguments: '["tuple",[]]',
      options: '["object",[]]',
      constructed: false,
    },
    {
      scope: "[]",
      position: 0,
      kind: "native",
      name: "starlette.middleware.errors.ServerErrorMiddleware",
      arguments: null,
      options: null,
      constructed: true,
    },
    {
      scope: "[]",
      position: 1,
      kind: "native",
      name: "app.Initialize",
      arguments: null,
      options: null,
      constructed: true,
    },
    {
      scope: "[]",
      position: 2,
      kind: "native",
      name: "app.Authorize",
      arguments: null,
      options: null,
      constructed: true,
    },
    {
      scope: "[]",
      position: 3,
      kind: "native",
      name: "starlette.middleware.exceptions.ExceptionMiddleware",
      arguments: null,
      options: null,
      constructed: true,
    },
    {
      scope: "[]",
      position: 4,
      kind: "native",
      name: "fastapi.middleware.asyncexitstack.AsyncExitStackMiddleware",
      arguments: null,
      options: null,
      constructed: true,
    },
    {
      scope: '[{"host":"api.example.test","kind":"host","name":"hosted"}]',
      position: 0,
      kind: "native",
      name: "starlette.middleware.errors.ServerErrorMiddleware",
      arguments: null,
      options: null,
      constructed: true,
    },
    {
      scope: '[{"host":"api.example.test","kind":"host","name":"hosted"}]',
      position: 1,
      kind: "native",
      name: "starlette.middleware.exceptions.ExceptionMiddleware",
      arguments: null,
      options: null,
      constructed: true,
    },
    {
      scope: '[{"host":"api.example.test","kind":"host","name":"hosted"}]',
      position: 2,
      kind: "native",
      name: "fastapi.middleware.asyncexitstack.AsyncExitStackMiddleware",
      arguments: null,
      options: null,
      constructed: true,
    },
    {
      scope: '[{"kind":"mount","name":"mounted","path":"/mounted"}]',
      position: 0,
      kind: "user",
      name: "app.Initialize",
      arguments: '["tuple",[]]',
      options: '["object",[["label",["string","child"]]]]',
      constructed: false,
    },
    {
      scope: '[{"kind":"mount","name":"mounted","path":"/mounted"}]',
      position: 0,
      kind: "native",
      name: "starlette.middleware.errors.ServerErrorMiddleware",
      arguments: null,
      options: null,
      constructed: true,
    },
    {
      scope: '[{"kind":"mount","name":"mounted","path":"/mounted"}]',
      position: 1,
      kind: "native",
      name: "app.Initialize",
      arguments: null,
      options: null,
      constructed: true,
    },
    {
      scope: '[{"kind":"mount","name":"mounted","path":"/mounted"}]',
      position: 2,
      kind: "native",
      name: "starlette.middleware.exceptions.ExceptionMiddleware",
      arguments: null,
      options: null,
      constructed: true,
    },
    {
      scope: '[{"kind":"mount","name":"mounted","path":"/mounted"}]',
      position: 3,
      kind: "native",
      name: "fastapi.middleware.asyncexitstack.AsyncExitStackMiddleware",
      arguments: null,
      options: null,
      constructed: true,
    },
  ],
  expectedLifespan: [
    {
      scope: "[]",
      position: 0,
      kind: "context",
      callable: "app.root_life",
      branch: "0",
    },
    {
      scope: "[]",
      position: 1,
      kind: "context",
      callable: "app.included_life",
      branch: "1",
    },
    {
      scope: '[{"host":"api.example.test","kind":"host","name":"hosted"}]',
      position: 0,
      kind: "context",
      callable: "fastapi.routing._DefaultLifespan",
      branch: "",
    },
    {
      scope: '[{"kind":"mount","name":"mounted","path":"/mounted"}]',
      position: 0,
      kind: "context",
      callable: "fastapi.routing._DefaultLifespan",
      branch: "",
    },
  ],
  expectedBindings: [
    {
      scope: "[]",
      position: 0,
      original: "app.original_settings",
      replacement: "app.configured_settings",
    },
  ],
  requests: [
    {
      protocol: "websocket",
      path: "/mounted/missing",
      host: "root.example.test",
      method: "WEBSOCKET",
      headers: [["authorization", "Bearer original"]],
      body: "",
      expected: {
        status: null,
        body: null,
        messages: ['{"code":1000,"reason":"","type":"websocket.close"}'],
      },
    },
    {
      protocol: "websocket",
      path: "/missing",
      host: "api.example.test",
      method: "WEBSOCKET",
      headers: [["authorization", "Bearer original"]],
      body: "",
      expected: {
        status: null,
        body: null,
        messages: ['{"code":1000,"reason":"","type":"websocket.close"}'],
      },
    },
    {
      protocol: "http",
      path: "/v1/catalog/items",
      host: "root.example.test",
      method: "GET",
      headers: [["authorization", "Bearer original"]],
      body: "",
      expected: {
        status: 200,
        body: '[{"id":1,"enabled":true},{"id":2,"enabled":true}]',
        messages: [],
      },
    },
    {
      protocol: "websocket",
      path: "/v1/catalog/socket",
      host: "root.example.test",
      method: "WEBSOCKET",
      headers: [["authorization", "Bearer original"]],
      body: "",
      expected: {
        status: null,
        body: null,
        messages: [
          '{"headers":[],"subprotocol":null,"type":"websocket.accept"}',
          '{"text":"{\\"ready\\":\\"socket-ready\\"}","type":"websocket.send"}',
          '{"code":1000,"reason":"","type":"websocket.close"}',
        ],
      },
    },
    {
      protocol: "http",
      path: "/mounted/items",
      host: "root.example.test",
      method: "GET",
      headers: [["authorization", "Bearer original"]],
      body: "",
      expected: {
        status: 200,
        body: '{"id":3,"enabled":true}',
        messages: [],
      },
    },
    {
      protocol: "http",
      path: "/items",
      host: "api.example.test",
      method: "GET",
      headers: [["authorization", "Bearer original"]],
      body: "",
      expected: {
        status: 200,
        body: '{"host":true}',
        messages: [],
      },
    },
    {
      protocol: "http",
      path: "/state",
      host: "root.example.test",
      method: "GET",
      headers: [["authorization", "Bearer original"]],
      body: "",
      expected: {
        status: 200,
        body: '["root.enter","included.enter"]',
        messages: [],
      },
    },
  ],
};
export async function project(
  t: TestContext,
  program = source,
  configuration: unknown = profile,
) {
  return fixture(t, {
    "pyproject.toml": "",
    ".checktrail/lifespan.reserved": "",
    "checktrail.json": JSON.stringify({
      schemaVersion: 1,
      projects: [{ path: ".", checks: ["python.fastapi-routes"] }],
    }),
    "checktrail.fastapi.json": JSON.stringify(configuration),
    "app.py": program,
  });
}
export async function run(
  t: TestContext,
  program = source,
  configuration: unknown = profile,
) {
  return validate(await project(t, program, configuration), { trusted: true });
}
