<Project Sdk="Microsoft.NET.Sdk"><PropertyGroup><TargetFramework>net10.0</TargetFramework><AssemblyName>Original.FSharp</AssemblyName><RootNamespace></RootNamespace><RestorePackagesWithLockFile>true</RestorePackagesWithLockFile><NuGetAudit>false</NuGetAudit><DebugType>portable</DebugType></PropertyGroup><ItemGroup><Compile Include="Counter.fs"/></ItemGroup></Project>
