import { capturedProcessOutputSchema } from "../dist/src/process-output.js";
import { windowsExecutionSchema } from "../dist/src/windows-execution.js";
import {
  importContextInputSchema,
  importContextReportSchema,
  importContextSummarySchema,
} from "../dist/src/import-context.js";
import { cppToolsConfigSchema } from "../dist/src/cpp-tools.js";
import { terraformConfigSchema } from "../dist/src/terraform.js";
import { kubeconformConfigSchema } from "../dist/src/kubeconform.js";
import { kustomizeConfigSchema } from "../dist/src/kustomize.js";
import { helmConfigSchema } from "../dist/src/helm.js";
import { swiftToolsConfigSchema } from "../dist/src/swift-tools.js";
import {
  rubyToolsConfigSchema,
  rubyToolsRepositorySchema,
} from "../dist/src/ruby-tools.js";
import { mkdir, writeFile } from "node:fs/promises";
import { URL } from "node:url";
import { z } from "zod";
import { format } from "prettier";
import {
  vueRouterConfigSchema,
  nuxtConfigSchema,
  externalManifestSchema,
  executableBundleSchema,
  externalReferenceSchema,
  externalRequestSchema,
  externalResultSchema,
  actionlintConfigSchema,
  goScopePolicySchema,
  goBuildPolicySchema,
  rustBuildPolicySchema,
  dotnetConfigSchema,
  dotnetBuildConfigSchema,
  dotnetBuildRepositorySchema,
  javaConfigSchema,
  checkstyleConfigSchema,
  mavenConfigSchema,
  gradleConfigSchema,
  mavenRepositorySchema,
  clangDatabaseSchema,
  mutationRecipeSchema,
  mutationReportSchema,
  mutationSummarySchema,
  reviewWorkflowAuditBindingSchema,
  reviewBenchmarkWorkerCommandSchema,
  reviewBenchmarkWorkerSummarySchema,
  reviewBenchmarkJudgeProfileSchema,
  reviewBenchmarkJudgmentSummarySchema,
  reviewBenchmarkJudgePacketSchema,
  reviewBenchmarkJudgmentOutputSchema,
  reviewBenchmarkJudgmentResponseSchema,
  reviewBenchmarkJudgeWorkerSummarySchema,
  reviewBenchmarkJudgmentArchiveSchema,
  reviewBenchmarkReferenceSchema,
  reviewBenchmarkPlanSchema,
  reviewBenchmarkCommandSchema,
  reviewBenchmarkSummarySchema,
  reviewBenchmarkPacketSchema,
  reviewBenchmarkJudgingSchema,
  reviewWorkflowNativeReceiptSchema,
  reviewWorkflowAuditOptionsSchema,
  reviewWorkflowAuditSummarySchema,
  reviewWorkflowLimitsSchema,
  reviewWorkflowResponseSchema,
  reviewWorkflowCommandSchema,
  reviewWorkflowAssignmentSchema,
  reviewWorkflowSummarySchema,
  reviewBenchmarkScoringProfileSchema,
  reviewBenchmarkScoreReportSchema,
  reviewBenchmarkScoreSummarySchema,
  reviewCalibrationInputSchema,
  reviewCalibrationReportSchema,
  reviewCalibrationSummarySchema,
  reviewCalibrationApplicationInputSchema,
  reviewCalibrationApplicationReportSchema,
  reviewCalibrationApplicationSummarySchema,
  reviewPairedProtocolSchema,
  reviewPairedInputSchema,
  reviewPairedReportSchema,
  reviewPairedSummarySchema,
  reviewScoringProtocolSchema,
  reviewScoringObservationSchema,
  reviewScoringInputSchema,
  reviewScoringReportSchema,
  reviewScoringSummarySchema,
  reviewVerificationRunSchema,
  reviewVerificationSummarySchema,
  reviewRefutationRunSchema,
  reviewRefutationSummarySchema,
  reviewProbeRecipeSchema,
  reviewProbeRunSchema,
  reviewProbeSummarySchema,
  reviewProviderConfigSchema,
  reviewCandidateSchema,
  reviewClaimProbabilitySchema,
  reviewModelOutputSchema,
  reviewProviderRunSchema,
  reviewProviderSummarySchema,
  hypothesisSelectionSchema,
  hypothesisPlanSchema,
  hypothesisSummarySchema,
  reviewSelectionSchema,
  reviewContextSchema,
  reviewContextSummarySchema,
  reviewAssessmentSchema,
  reviewReceiptSchema,
  reviewReceiptSummarySchema,
  guidanceContextSchema,
  guidanceReportSchema,
  guidanceSummarySchema,
  dependencyGraphSchema,
  architecturePolicySchema,
  architectureReportSchema,
  architectureSummarySchema,
  runtimeInventorySchema,
  runtimeComparisonSchema,
  runtimeComparisonSummarySchema,
  findingBaselineSchema,
  findingComparisonSchema,
  findingComparisonSummarySchema,
  junitImportSchema,
  contractBundleSchema,
  contractReportSchema,
  contractSummarySchema,
  laravelConfigSchema,
  djangoConfigSchema,
  fastapiConfigSchema,
  configSchema,
  policyPackSchema,
  planSchema,
  planSummarySchema,
  reportSchema,
  reportSummarySchema,
} from "../dist/src/schemas.js";

await mkdir(new URL("../schemas/", import.meta.url), { recursive: true });
for (const [name, schema] of Object.entries({
  "captured-process-output": capturedProcessOutputSchema,
  "windows-execution": windowsExecutionSchema,
  "vue-router-config": vueRouterConfigSchema,
  "nuxt-config": nuxtConfigSchema,
  "external-manifest": externalManifestSchema,
  "executable-bundle": executableBundleSchema,
  "external-reference": externalReferenceSchema,
  "external-request": externalRequestSchema,
  "external-result": externalResultSchema,
  "actionlint-config": actionlintConfigSchema,
  "go-scope-policy": goScopePolicySchema,
  "go-build-policy": goBuildPolicySchema,
  "rust-build-policy": rustBuildPolicySchema,
  "dotnet-config": dotnetConfigSchema,
  "cpp-tools-config": cppToolsConfigSchema,
  "kubeconform-config": kubeconformConfigSchema,
  "kustomize-config": kustomizeConfigSchema,
  "helm-config": helmConfigSchema,
  "terraform-config": terraformConfigSchema,
  "swift-tools-config": swiftToolsConfigSchema,
  "ruby-tools-config": rubyToolsConfigSchema,
  "ruby-tools-repository": rubyToolsRepositorySchema,
  "dotnet-build-config": dotnetBuildConfigSchema,
  "dotnet-build-repository": dotnetBuildRepositorySchema,
  "java-config": javaConfigSchema,
  "checkstyle-config": checkstyleConfigSchema,
  "maven-config": mavenConfigSchema,
  "gradle-config": gradleConfigSchema,
  "maven-repository": mavenRepositorySchema,
  "clang-database": clangDatabaseSchema,
  "mutation-recipe": mutationRecipeSchema,
  "mutation-report": mutationReportSchema,
  "mutation-summary": mutationSummarySchema,
  "review-calibration-input": reviewCalibrationInputSchema,
  "review-calibration-report": reviewCalibrationReportSchema,
  "review-calibration-summary": reviewCalibrationSummarySchema,
  "review-calibration-application-input":
    reviewCalibrationApplicationInputSchema,
  "review-calibration-application-report":
    reviewCalibrationApplicationReportSchema,
  "review-calibration-application-summary":
    reviewCalibrationApplicationSummarySchema,
  "review-paired-protocol": reviewPairedProtocolSchema,
  "review-paired-input": reviewPairedInputSchema,
  "review-paired-report": reviewPairedReportSchema,
  "review-paired-summary": reviewPairedSummarySchema,
  "review-scoring-protocol": reviewScoringProtocolSchema,
  "review-scoring-observation": reviewScoringObservationSchema,
  "review-scoring-input": reviewScoringInputSchema,
  "review-scoring-report": reviewScoringReportSchema,
  "review-scoring-summary": reviewScoringSummarySchema,
  "review-workflow-audit-binding": reviewWorkflowAuditBindingSchema,
  "review-benchmark-worker-command": reviewBenchmarkWorkerCommandSchema,
  "review-benchmark-worker-summary": reviewBenchmarkWorkerSummarySchema,
  "review-benchmark-judge-profile": reviewBenchmarkJudgeProfileSchema,
  "review-benchmark-judgment-summary": reviewBenchmarkJudgmentSummarySchema,
  "review-benchmark-judge-packet": reviewBenchmarkJudgePacketSchema,
  "review-benchmark-judgment-output": reviewBenchmarkJudgmentOutputSchema,
  "review-benchmark-judgment-response": reviewBenchmarkJudgmentResponseSchema,
  "review-benchmark-judge-worker-summary":
    reviewBenchmarkJudgeWorkerSummarySchema,
  "review-benchmark-judgment-archive": reviewBenchmarkJudgmentArchiveSchema,
  "review-benchmark-reference": reviewBenchmarkReferenceSchema,
  "review-benchmark-plan": reviewBenchmarkPlanSchema,
  "review-benchmark-scoring-profile": reviewBenchmarkScoringProfileSchema,
  "review-benchmark-score-report": reviewBenchmarkScoreReportSchema,
  "review-benchmark-score-summary": reviewBenchmarkScoreSummarySchema,
  "review-benchmark-command": reviewBenchmarkCommandSchema,
  "review-benchmark-summary": reviewBenchmarkSummarySchema,
  "review-benchmark-packet": reviewBenchmarkPacketSchema,
  "review-benchmark-judging": reviewBenchmarkJudgingSchema,
  "review-workflow-native-receipt": reviewWorkflowNativeReceiptSchema,
  "review-workflow-audit-options": reviewWorkflowAuditOptionsSchema,
  "review-workflow-audit-summary": reviewWorkflowAuditSummarySchema,
  "review-workflow-limits": reviewWorkflowLimitsSchema,
  "review-workflow-response": reviewWorkflowResponseSchema,
  "review-workflow-command": reviewWorkflowCommandSchema,
  "review-workflow-assignment": reviewWorkflowAssignmentSchema,
  "review-workflow-summary": reviewWorkflowSummarySchema,
  "review-verification-run": reviewVerificationRunSchema,
  "review-verification-summary": reviewVerificationSummarySchema,
  "review-refutation-run": reviewRefutationRunSchema,
  "review-refutation-summary": reviewRefutationSummarySchema,
  "review-probe-recipe": reviewProbeRecipeSchema,
  "review-probe-run": reviewProbeRunSchema,
  "review-probe-summary": reviewProbeSummarySchema,
  "review-provider-config": reviewProviderConfigSchema,
  "review-candidate": reviewCandidateSchema,
  "review-claim-probability": reviewClaimProbabilitySchema,
  "review-model-output": reviewModelOutputSchema,
  "review-provider-run": reviewProviderRunSchema,
  "review-provider-summary": reviewProviderSummarySchema,
  "review-hypothesis-selection": hypothesisSelectionSchema,
  "review-hypothesis-plan": hypothesisPlanSchema,
  "review-hypothesis-summary": hypothesisSummarySchema,
  "review-selection": reviewSelectionSchema,
  "review-context": reviewContextSchema,
  "review-context-summary": reviewContextSummarySchema,
  "review-assessment": reviewAssessmentSchema,
  "review-receipt": reviewReceiptSchema,
  "review-receipt-summary": reviewReceiptSummarySchema,
  "guidance-context": guidanceContextSchema,
  "guidance-report": guidanceReportSchema,
  "guidance-summary": guidanceSummarySchema,
  "dependency-graph": dependencyGraphSchema,
  "import-context-input": importContextInputSchema,
  "import-context-report": importContextReportSchema,
  "import-context-summary": importContextSummarySchema,
  "architecture-policy": architecturePolicySchema,
  "architecture-report": architectureReportSchema,
  "architecture-summary": architectureSummarySchema,
  "runtime-inventory": runtimeInventorySchema,
  "runtime-comparison": runtimeComparisonSchema,
  "runtime-comparison-summary": runtimeComparisonSummarySchema,
  "finding-baseline": findingBaselineSchema,
  "finding-comparison": findingComparisonSchema,
  "finding-comparison-summary": findingComparisonSummarySchema,
  junit: junitImportSchema,
  "contract-bundle": contractBundleSchema,
  "contract-report": contractReportSchema,
  "contract-summary": contractSummarySchema,
  "laravel-config": laravelConfigSchema,
  "django-config": djangoConfigSchema,
  "fastapi-config": fastapiConfigSchema,
  config: configSchema,
  "policy-pack": policyPackSchema,
  plan: planSchema,
  "plan-summary": planSummarySchema,
  report: reportSchema,
  "report-summary": reportSummarySchema,
})) {
  await writeFile(
    new URL(`../schemas/${name}.schema.json`, import.meta.url),
    await format(
      JSON.stringify(
        z.toJSONSchema(
          schema,
          name === "dotnet-build-config" ? { io: "input" } : {},
        ),
      ),
      { parser: "json" },
    ),
  );
}
