import { mkdir, writeFile } from "node:fs/promises";
import { URL } from "node:url";
import { z } from "zod";
import { format } from "prettier";
import {
  vueRouterConfigSchema,
  nuxtConfigSchema,
  externalManifestSchema,
  externalReferenceSchema,
  externalRequestSchema,
  externalResultSchema,
  actionlintConfigSchema,
  goScopePolicySchema,
  goBuildPolicySchema,
  rustBuildPolicySchema,
  dotnetConfigSchema,
  javaConfigSchema,
  clangDatabaseSchema,
  mutationRecipeSchema,
  mutationReportSchema,
  mutationSummarySchema,
  reviewWorkflowAuditBindingSchema,
  reviewBenchmarkWorkerCommandSchema,
  reviewBenchmarkWorkerSummarySchema,
  reviewBenchmarkJudgeProfileSchema,
  reviewBenchmarkJudgmentSummarySchema,
  reviewBenchmarkJudgePacketSchema,
  reviewBenchmarkJudgmentOutputSchema,
  reviewBenchmarkJudgmentResponseSchema,
  reviewBenchmarkJudgeWorkerSummarySchema,
  reviewBenchmarkJudgmentArchiveSchema,
  reviewBenchmarkReferenceSchema,
  reviewBenchmarkPlanSchema,
  reviewBenchmarkCommandSchema,
  reviewBenchmarkSummarySchema,
  reviewBenchmarkPacketSchema,
  reviewBenchmarkJudgingSchema,
  reviewWorkflowNativeReceiptSchema,
  reviewWorkflowAuditOptionsSchema,
  reviewWorkflowAuditSummarySchema,
  reviewWorkflowLimitsSchema,
  reviewWorkflowResponseSchema,
  reviewWorkflowCommandSchema,
  reviewWorkflowAssignmentSchema,
  reviewWorkflowSummarySchema,
  reviewScoringProtocolSchema,
  reviewScoringObservationSchema,
  reviewScoringInputSchema,
  reviewScoringReportSchema,
  reviewScoringSummarySchema,
  reviewVerificationRunSchema,
  reviewVerificationSummarySchema,
  reviewRefutationRunSchema,
  reviewRefutationSummarySchema,
  reviewProbeRecipeSchema,
  reviewProbeRunSchema,
  reviewProbeSummarySchema,
  reviewProviderConfigSchema,
  reviewCandidateSchema,
  reviewModelOutputSchema,
  reviewProviderRunSchema,
  reviewProviderSummarySchema,
  hypothesisSelectionSchema,
  hypothesisPlanSchema,
  hypothesisSummarySchema,
  reviewSelectionSchema,
  reviewContextSchema,
  reviewContextSummarySchema,
  reviewAssessmentSchema,
  reviewReceiptSchema,
  reviewReceiptSummarySchema,
  guidanceContextSchema,
  guidanceReportSchema,
  guidanceSummarySchema,
  dependencyGraphSchema,
  architecturePolicySchema,
  architectureReportSchema,
  architectureSummarySchema,
  runtimeInventorySchema,
  runtimeComparisonSchema,
  runtimeComparisonSummarySchema,
  findingBaselineSchema,
  findingComparisonSchema,
  findingComparisonSummarySchema,
  junitImportSchema,
  contractBundleSchema,
  contractReportSchema,
  contractSummarySchema,
  laravelConfigSchema,
  djangoConfigSchema,
  fastapiConfigSchema,
  configSchema,
  policyPackSchema,
  planSchema,
  planSummarySchema,
  reportSchema,
  reportSummarySchema,
} from "../dist/src/schemas.js";

await mkdir(new URL("../schemas/", import.meta.url), { recursive: true });
for (const [name, schema] of Object.entries({
  "vue-router-config": vueRouterConfigSchema,
  "nuxt-config": nuxtConfigSchema,
  "external-manifest": externalManifestSchema,
  "external-reference": externalReferenceSchema,
  "external-request": externalRequestSchema,
  "external-result": externalResultSchema,
  "actionlint-config": actionlintConfigSchema,
  "go-scope-policy": goScopePolicySchema,
  "go-build-policy": goBuildPolicySchema,
  "rust-build-policy": rustBuildPolicySchema,
  "dotnet-config": dotnetConfigSchema,
  "java-config": javaConfigSchema,
  "clang-database": clangDatabaseSchema,
  "mutation-recipe": mutationRecipeSchema,
  "mutation-report": mutationReportSchema,
  "mutation-summary": mutationSummarySchema,
  "review-scoring-protocol": reviewScoringProtocolSchema,
  "review-scoring-observation": reviewScoringObservationSchema,
  "review-scoring-input": reviewScoringInputSchema,
  "review-scoring-report": reviewScoringReportSchema,
  "review-scoring-summary": reviewScoringSummarySchema,
  "review-workflow-audit-binding": reviewWorkflowAuditBindingSchema,
  "review-benchmark-worker-command": reviewBenchmarkWorkerCommandSchema,
  "review-benchmark-worker-summary": reviewBenchmarkWorkerSummarySchema,
  "review-benchmark-judge-profile": reviewBenchmarkJudgeProfileSchema,
  "review-benchmark-judgment-summary": reviewBenchmarkJudgmentSummarySchema,
  "review-benchmark-judge-packet": reviewBenchmarkJudgePacketSchema,
  "review-benchmark-judgment-output": reviewBenchmarkJudgmentOutputSchema,
  "review-benchmark-judgment-response": reviewBenchmarkJudgmentResponseSchema,
  "review-benchmark-judge-worker-summary":
    reviewBenchmarkJudgeWorkerSummarySchema,
  "review-benchmark-judgment-archive": reviewBenchmarkJudgmentArchiveSchema,
  "review-benchmark-reference": reviewBenchmarkReferenceSchema,
  "review-benchmark-plan": reviewBenchmarkPlanSchema,
  "review-benchmark-command": reviewBenchmarkCommandSchema,
  "review-benchmark-summary": reviewBenchmarkSummarySchema,
  "review-benchmark-packet": reviewBenchmarkPacketSchema,
  "review-benchmark-judging": reviewBenchmarkJudgingSchema,
  "review-workflow-native-receipt": reviewWorkflowNativeReceiptSchema,
  "review-workflow-audit-options": reviewWorkflowAuditOptionsSchema,
  "review-workflow-audit-summary": reviewWorkflowAuditSummarySchema,
  "review-workflow-limits": reviewWorkflowLimitsSchema,
  "review-workflow-response": reviewWorkflowResponseSchema,
  "review-workflow-command": reviewWorkflowCommandSchema,
  "review-workflow-assignment": reviewWorkflowAssignmentSchema,
  "review-workflow-summary": reviewWorkflowSummarySchema,
  "review-verification-run": reviewVerificationRunSchema,
  "review-verification-summary": reviewVerificationSummarySchema,
  "review-refutation-run": reviewRefutationRunSchema,
  "review-refutation-summary": reviewRefutationSummarySchema,
  "review-probe-recipe": reviewProbeRecipeSchema,
  "review-probe-run": reviewProbeRunSchema,
  "review-probe-summary": reviewProbeSummarySchema,
  "review-provider-config": reviewProviderConfigSchema,
  "review-candidate": reviewCandidateSchema,
  "review-model-output": reviewModelOutputSchema,
  "review-provider-run": reviewProviderRunSchema,
  "review-provider-summary": reviewProviderSummarySchema,
  "review-hypothesis-selection": hypothesisSelectionSchema,
  "review-hypothesis-plan": hypothesisPlanSchema,
  "review-hypothesis-summary": hypothesisSummarySchema,
  "review-selection": reviewSelectionSchema,
  "review-context": reviewContextSchema,
  "review-context-summary": reviewContextSummarySchema,
  "review-assessment": reviewAssessmentSchema,
  "review-receipt": reviewReceiptSchema,
  "review-receipt-summary": reviewReceiptSummarySchema,
  "guidance-context": guidanceContextSchema,
  "guidance-report": guidanceReportSchema,
  "guidance-summary": guidanceSummarySchema,
  "dependency-graph": dependencyGraphSchema,
  "architecture-policy": architecturePolicySchema,
  "architecture-report": architectureReportSchema,
  "architecture-summary": architectureSummarySchema,
  "runtime-inventory": runtimeInventorySchema,
  "runtime-comparison": runtimeComparisonSchema,
  "runtime-comparison-summary": runtimeComparisonSummarySchema,
  "finding-baseline": findingBaselineSchema,
  "finding-comparison": findingComparisonSchema,
  "finding-comparison-summary": findingComparisonSummarySchema,
  junit: junitImportSchema,
  "contract-bundle": contractBundleSchema,
  "contract-report": contractReportSchema,
  "contract-summary": contractSummarySchema,
  "laravel-config": laravelConfigSchema,
  "django-config": djangoConfigSchema,
  "fastapi-config": fastapiConfigSchema,
  config: configSchema,
  "policy-pack": policyPackSchema,
  plan: planSchema,
  "plan-summary": planSummarySchema,
  report: reportSchema,
  "report-summary": reportSummarySchema,
})) {
  await writeFile(
    new URL(`../schemas/${name}.schema.json`, import.meta.url),
    await format(JSON.stringify(z.toJSONSchema(schema)), { parser: "json" }),
  );
}
