<Project Sdk="Microsoft.NET.Sdk"><PropertyGroup><TargetFramework>net10.0</TargetFramework><AssemblyName>Original.VisualBasicTests</AssemblyName><RootNamespace></RootNamespace><RestorePackagesWithLockFile>true</RestorePackagesWithLockFile><NuGetAudit>false</NuGetAudit><DebugType>portable</DebugType><IsTestProject>true</IsTestProject><IsPackable>false</IsPackable></PropertyGroup><ItemGroup><PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.10.1"/><PackageReference Include="NUnit" Version="4.6.1"/><PackageReference Include="NUnit3TestAdapter" Version="5.0.0"/></ItemGroup><ItemGroup><ProjectReference Include="../VisualBasic/VisualBasic.vbproj"/></ItemGroup></Project>
