// Native rule instances and SDK modules observed in the byte-pinned full-mode profile.
export const detektFullRules = [
  {
    set: "complexity",
    id: "CognitiveComplexMethod",
    active: false,
    severity: "Error",
    className: "dev.detekt.rules.complexity.CognitiveComplexMethod",
    requiresAnalysisApi: false,
  },
  {
    set: "complexity",
    id: "ComplexCondition",
    active: true,
    severity: "Error",
    className: "dev.detekt.rules.complexity.ComplexCondition",
    requiresAnalysisApi: false,
  },
  {
    set: "complexity",
    id: "ComplexInterface",
    active: false,
    severity: "Error",
    className: "dev.detekt.rules.complexity.ComplexInterface",
    requiresAnalysisApi: false,
  },
  {
    set: "complexity",
    id: "CyclomaticComplexMethod",
    active: true,
    severity: "Error",
    className: "dev.detekt.rules.complexity.CyclomaticComplexMethod",
    requiresAnalysisApi: false,
  },
  {
    set: "complexity",
    id: "LabeledExpression",
    active: false,
    severity: "Error",
    className: "dev.detekt.rules.complexity.LabeledExpression",
    requiresAnalysisApi: false,
  },
  {
    set: "complexity",
    id: "LargeClass",
    active: true,
    severity: "Error",
    className: "dev.detekt.rules.complexity.LargeClass",
    requiresAnalysisApi: false,
  },
  {
    set: "complexity",
    id: "LongMethod",
    active: true,
    severity: "Error",
    className: "dev.detekt.rules.complexity.LongMethod",
    requiresAnalysisApi: false,
  },
  {
    set: "complexity",
    id: "LongParameterList",
    active: true,
    severity: "Error",
    className: "dev.detekt.rules.complexity.LongParameterList",
    requiresAnalysisApi: true,
  },
  {
    set: "complexity",
    id: "MethodOverloading",
    active: false,
    severity: "Error",
    className: "dev.detekt.rules.complexity.MethodOverloading",
    requiresAnalysisApi: false,
  },
  {
    set: "complexity",
    id: "NamedArguments",
    active: false,
    severity: "Error",
    className: "dev.detekt.rules.complexity.NamedArguments",
    requiresAnalysisApi: true,
  },
  {
    set: "complexity",
    id: "NestedBlockDepth",
    active: true,
    severity: "Error",
    className: "dev.detekt.rules.complexity.NestedBlockDepth",
    requiresAnalysisApi: false,
  },
  {
    set: "complexity",
    id: "NestedScopeFunctions",
    active: false,
    severity: "Error",
    className: "dev.detekt.rules.complexity.NestedScopeFunctions",
    requiresAnalysisApi: true,
  },
  {
    set: "complexity",
    id: "ReplaceSafeCallChainWithRun",
    active: false,
    severity: "Error",
    className: "dev.detekt.rules.complexity.ReplaceSafeCallChainWithRun",
    requiresAnalysisApi: true,
  },
  {
    set: "complexity",
    id: "StringLiteralDuplication",
    active: false,
    severity: "Error",
    className: "dev.detekt.rules.complexity.StringLiteralDuplication",
    requiresAnalysisApi: false,
  },
  {
    set: "complexity",
    id: "TooManyFunctions",
    active: true,
    severity: "Error",
    className: "dev.detekt.rules.complexity.TooManyFunctions",
    requiresAnalysisApi: false,
  },
  {
    set: "coroutines",
    id: "CoroutineLaunchedInTestWithoutRunTest",
    active: false,
    severity: "Error",
    className:
      "dev.detekt.rules.coroutines.CoroutineLaunchedInTestWithoutRunTest",
    requiresAnalysisApi: true,
  },
  {
    set: "coroutines",
    id: "GlobalCoroutineUsage",
    active: false,
    severity: "Error",
    className: "dev.detekt.rules.coroutines.GlobalCoroutineUsage",
    requiresAnalysisApi: false,
  },
  {
    set: "coroutines",
    id: "InjectDispatcher",
    active: true,
    severity: "Error",
    className: "dev.detekt.rules.coroutines.InjectDispatcher",
    requiresAnalysisApi: true,
  },
  {
    set: "coroutines",
    id: "RedundantSuspendModifier",
    active: true,
    severity: "Error",
    className: "dev.detekt.rules.coroutines.RedundantSuspendModifier",
    requiresAnalysisApi: true,
  },
  {
    set: "coroutines",
    id: "SleepInsteadOfDelay",
    active: true,
    severity: "Error",
    className: "dev.detekt.rules.coroutines.SleepInsteadOfDelay",
    requiresAnalysisApi: true,
  },
  {
    set: "coroutines",
    id: "SuspendFunInFinallySection",
    active: false,
    severity: "Error",
    className: "dev.detekt.rules.coroutines.SuspendFunInFinallySection",
    requiresAnalysisApi: true,
  },
  {
    set: "coroutines",
    id: "SuspendFunSwallowedCancellation",
    active: false,
    severity: "Error",
    className: "dev.detekt.rules.coroutines.SuspendFunSwallowedCancellation",
    requiresAnalysisApi: true,
  },
  {
    set: "coroutines",
    id: "SuspendFunWithCoroutineScopeReceiver",
    active: false,
    severity: "Error",
    className:
      "dev.detekt.rules.coroutines.SuspendFunWithCoroutineScopeReceiver",
    requiresAnalysisApi: true,
  },
  {
    set: "coroutines",
    id: "SuspendFunWithFlowReturnType",
    active: true,
    severity: "Error",
    className: "dev.detekt.rules.coroutines.SuspendFunWithFlowReturnType",
    requiresAnalysisApi: true,
  },
  {
    set: "comments",
    id: "AbsentOrWrongFileLicense",
    active: false,
    severity: "Error",
    className: "dev.detekt.rules.comments.AbsentOrWrongFileLicense",
    requiresAnalysisApi: false,
  },
  {
    set: "comments",
    id: "DeprecatedBlockTag",
    active: false,
    severity: "Error",
    className: "dev.detekt.rules.comments.DeprecatedBlockTag",
    requiresAnalysisApi: false,
  },
  {
    set: "comments",
    id: "DocumentationOverPrivateFunction",
    active: false,
    severity: "Error",
    className: "dev.detekt.rules.comments.DocumentationOverPrivateFunction",
    requiresAnalysisApi: false,
  },
  {
    set: "comments",
    id: "DocumentationOverPrivateProperty",
    active: false,
    severity: "Error",
    className: "dev.detekt.rules.comments.DocumentationOverPrivateProperty",
    requiresAnalysisApi: false,
  },
  {
    set: "comments",
    id: "EndOfSentenceFormat",
    active: false,
    severity: "Error",
    className: "dev.detekt.rules.comments.EndOfSentenceFormat",
    requiresAnalysisApi: false,
  },
  {
    set: "comments",
    id: "KDocReferencesNonPublicProperty",
    active: false,
    severity: "Error",
    className: "dev.detekt.rules.comments.KDocReferencesNonPublicProperty",
    requiresAnalysisApi: false,
  },
  {
    set: "comments",
    id: "OutdatedDocumentation",
    active: false,
    severity: "Error",
    className: "dev.detekt.rules.comments.OutdatedDocumentation",
    requiresAnalysisApi: false,
  },
  {
    set: "comments",
    id: "UndocumentedPublicClass",
    active: false,
    severity: "Error",
    className: "dev.detekt.rules.comments.UndocumentedPublicClass",
    requiresAnalysisApi: false,
  },
  {
    set: "comments",
    id: "UndocumentedPublicFunction",
    active: false,
    severity: "Error",
    className: "dev.detekt.rules.comments.UndocumentedPublicFunction",
    requiresAnalysisApi: false,
  },
  {
    set: "comments",
    id: "UndocumentedPublicProperty",
    active: false,
    severity: "Error",
    className: "dev.detekt.rules.comments.UndocumentedPublicProperty",
    requiresAnalysisApi: false,
  },
  {
    set: "empty-blocks",
    id: "EmptyCatchBlock",
    active: true,
    severity: "Error",
    className: "dev.detekt.rules.emptyblocks.EmptyCatchBlock",
    requiresAnalysisApi: false,
  },
  {
    set: "empty-blocks",
    id: "EmptyClassBlock",
    active: true,
    severity: "Error",
    className: "dev.detekt.rules.emptyblocks.EmptyClassBlock",
    requiresAnalysisApi: false,
  },
  {
    set: "empty-blocks",
    id: "EmptyDefaultConstructor",
    active: true,
    severity: "Error",
    className: "dev.detekt.rules.emptyblocks.EmptyDefaultConstructor",
    requiresAnalysisApi: false,
  },
  {
    set: "empty-blocks",
    id: "EmptyDoWhileBlock",
    active: true,
    severity: "Error",
    className: "dev.detekt.rules.emptyblocks.EmptyDoWhileBlock",
    requiresAnalysisApi: false,
  },
  {
    set: "empty-blocks",
    id: "EmptyElseBlock",
    active: true,
    severity: "Error",
    className: "dev.detekt.rules.emptyblocks.EmptyElseBlock",
    requiresAnalysisApi: false,
  },
  {
    set: "empty-blocks",
    id: "EmptyFinallyBlock",
    active: true,
    severity: "Error",
    className: "dev.detekt.rules.emptyblocks.EmptyFinallyBlock",
    requiresAnalysisApi: false,
  },
  {
    set: "empty-blocks",
    id: "EmptyForBlock",
    active: true,
    severity: "Error",
    className: "dev.detekt.rules.emptyblocks.EmptyForBlock",
    requiresAnalysisApi: false,
  },
  {
    set: "empty-blocks",
    id: "EmptyFunctionBlock",
    active: true,
    severity: "Error",
    className: "dev.detekt.rules.emptyblocks.EmptyFunctionBlock",
    requiresAnalysisApi: false,
  },
  {
    set: "empty-blocks",
    id: "EmptyIfBlock",
    active: true,
    severity: "Error",
    className: "dev.detekt.rules.emptyblocks.EmptyIfBlock",
    requiresAnalysisApi: false,
  },
  {
    set: "empty-blocks",
    id: "EmptyInitBlock",
    active: true,
    severity: "Error",
    className: "dev.detekt.rules.emptyblocks.EmptyInitBlock",
    requiresAnalysisApi: false,
  },
  {
    set: "empty-blocks",
    id: "EmptyKotlinFile",
    active: true,
    severity: "Error",
    className: "dev.detekt.rules.emptyblocks.EmptyKotlinFile",
    requiresAnalysisApi: false,
  },
  {
    set: "empty-blocks",
    id: "EmptySecondaryConstructor",
    active: true,
    severity: "Error",
    className: "dev.detekt.rules.emptyblocks.EmptySecondaryConstructor",
    requiresAnalysisApi: false,
  },
  {
    set: "empty-blocks",
    id: "EmptyTryBlock",
    active: true,
    severity: "Error",
    className: "dev.detekt.rules.emptyblocks.EmptyTryBlock",
    requiresAnalysisApi: false,
  },
  {
    set: "empty-blocks",
    id: "EmptyWhenBlock",
    active: true,
    severity: "Error",
    className: "dev.detekt.rules.emptyblocks.EmptyWhenBlock",
    requiresAnalysisApi: false,
  },
  {
    set: "empty-blocks",
    id: "EmptyWhileBlock",
    active: true,
    severity: "Error",
    className: "dev.detekt.rules.emptyblocks.EmptyWhileBlock",
    requiresAnalysisApi: false,
  },
  {
    set: "potential-bugs",
    id: "AvoidReferentialEquality",
    active: true,
    severity: "Error",
    className: "dev.detekt.rules.potentialbugs.AvoidReferentialEquality",
    requiresAnalysisApi: true,
  },
  {
    set: "potential-bugs",
    id: "CastNullableToNonNullableType",
    active: false,
    severity: "Error",
    className: "dev.detekt.rules.potentialbugs.CastNullableToNonNullableType",
    requiresAnalysisApi: true,
  },
  {
    set: "potential-bugs",
    id: "CastToNullableType",
    active: false,
    severity: "Error",
    className: "dev.detekt.rules.potentialbugs.CastToNullableType",
    requiresAnalysisApi: true,
  },
  {
    set: "potential-bugs",
    id: "CharArrayToStringCall",
    active: false,
    severity: "Error",
    className: "dev.detekt.rules.potentialbugs.CharArrayToStringCall",
    requiresAnalysisApi: true,
  },
  {
    set: "potential-bugs",
    id: "Deprecation",
    active: false,
    severity: "Error",
    className: "dev.detekt.rules.potentialbugs.Deprecation",
    requiresAnalysisApi: true,
  },
  {
    set: "potential-bugs",
    id: "DontDowncastCollectionTypes",
    active: false,
    severity: "Error",
    className: "dev.detekt.rules.potentialbugs.DontDowncastCollectionTypes",
    requiresAnalysisApi: true,
  },
  {
    set: "potential-bugs",
    id: "DoubleMutabilityForCollection",
    active: true,
    severity: "Error",
    className: "dev.detekt.rules.potentialbugs.DoubleMutabilityForCollection",
    requiresAnalysisApi: true,
  },
  {
    set: "potential-bugs",
    id: "ElseCaseInsteadOfExhaustiveWhen",
    active: false,
    severity: "Error",
    className: "dev.detekt.rules.potentialbugs.ElseCaseInsteadOfExhaustiveWhen",
    requiresAnalysisApi: true,
  },
  {
    set: "potential-bugs",
    id: "EqualsAlwaysReturnsTrueOrFalse",
    active: true,
    severity: "Error",
    className: "dev.detekt.rules.potentialbugs.EqualsAlwaysReturnsTrueOrFalse",
    requiresAnalysisApi: false,
  },
  {
    set: "potential-bugs",
    id: "EqualsWithHashCodeExist",
    active: true,
    severity: "Error",
    className: "dev.detekt.rules.potentialbugs.EqualsWithHashCodeExist",
    requiresAnalysisApi: false,
  },
  {
    set: "potential-bugs",
    id: "ExitOutsideMain",
    active: false,
    severity: "Error",
    className: "dev.detekt.rules.potentialbugs.ExitOutsideMain",
    requiresAnalysisApi: true,
  },
  {
    set: "potential-bugs",
    id: "ExplicitGarbageCollectionCall",
    active: true,
    severity: "Error",
    className: "dev.detekt.rules.potentialbugs.ExplicitGarbageCollectionCall",
    requiresAnalysisApi: false,
  },
  {
    set: "potential-bugs",
    id: "HasPlatformType",
    active: true,
    severity: "Error",
    className: "dev.detekt.rules.potentialbugs.HasPlatformType",
    requiresAnalysisApi: true,
  },
  {
    set: "potential-bugs",
    id: "IgnoredReturnValue",
    active: true,
    severity: "Error",
    className: "dev.detekt.rules.potentialbugs.IgnoredReturnValue",
    requiresAnalysisApi: true,
  },
  {
    set: "potential-bugs",
    id: "ImplicitDefaultLocale",
    active: true,
    severity: "Error",
    className: "dev.detekt.rules.potentialbugs.ImplicitDefaultLocale",
    requiresAnalysisApi: true,
  },
  {
    set: "potential-bugs",
    id: "ImplicitUnitReturnType",
    active: false,
    severity: "Error",
    className: "dev.detekt.rules.potentialbugs.ImplicitUnitReturnType",
    requiresAnalysisApi: true,
  },
  {
    set: "potential-bugs",
    id: "InvalidRange",
    active: true,
    severity: "Error",
    className: "dev.detekt.rules.potentialbugs.InvalidRange",
    requiresAnalysisApi: false,
  },
  {
    set: "potential-bugs",
    id: "IteratorHasNextCallsNextMethod",
    active: true,
    severity: "Error",
    className: "dev.detekt.rules.potentialbugs.IteratorHasNextCallsNextMethod",
    requiresAnalysisApi: false,
  },
  {
    set: "potential-bugs",
    id: "IteratorNotThrowingNoSuchElementException",
    active: true,
    severity: "Error",
    className:
      "dev.detekt.rules.potentialbugs.IteratorNotThrowingNoSuchElementException",
    requiresAnalysisApi: false,
  },
  {
    set: "potential-bugs",
    id: "LateinitUsage",
    active: false,
    severity: "Error",
    className: "dev.detekt.rules.potentialbugs.LateinitUsage",
    requiresAnalysisApi: false,
  },
  {
    set: "potential-bugs",
    id: "MapGetWithNotNullAssertionOperator",
    active: true,
    severity: "Error",
    className:
      "dev.detekt.rules.potentialbugs.MapGetWithNotNullAssertionOperator",
    requiresAnalysisApi: true,
  },
  {
    set: "potential-bugs",
    id: "MissingPackageDeclaration",
    active: false,
    severity: "Error",
    className: "dev.detekt.rules.potentialbugs.MissingPackageDeclaration",
    requiresAnalysisApi: false,
  },
  {
    set: "potential-bugs",
    id: "MissingSuperCall",
    active: false,
    severity: "Error",
    className: "dev.detekt.rules.potentialbugs.MissingSuperCall",
    requiresAnalysisApi: true,
  },
  {
    set: "potential-bugs",
    id: "MissingUseCall",
    active: false,
    severity: "Error",
    className: "dev.detekt.rules.potentialbugs.MissingUseCall",
    requiresAnalysisApi: true,
  },
  {
    set: "potential-bugs",
    id: "NullCheckOnMutableProperty",
    active: false,
    severity: "Error",
    className: "dev.detekt.rules.potentialbugs.NullCheckOnMutableProperty",
    requiresAnalysisApi: true,
  },
  {
    set: "potential-bugs",
    id: "NullableToStringCall",
    active: false,
    severity: "Error",
    className: "dev.detekt.rules.potentialbugs.NullableToStringCall",
    requiresAnalysisApi: true,
  },
  {
    set: "potential-bugs",
    id: "PropertyUsedBeforeDeclaration",
    active: false,
    severity: "Error",
    className: "dev.detekt.rules.potentialbugs.PropertyUsedBeforeDeclaration",
    requiresAnalysisApi: true,
  },
  {
    set: "potential-bugs",
    id: "UnconditionalJumpStatementInLoop",
    active: false,
    severity: "Error",
    className:
      "dev.detekt.rules.potentialbugs.UnconditionalJumpStatementInLoop",
    requiresAnalysisApi: false,
  },
  {
    set: "potential-bugs",
    id: "UnnamedParameterUse",
    active: false,
    severity: "Error",
    className: "dev.detekt.rules.potentialbugs.UnnamedParameterUse",
    requiresAnalysisApi: true,
  },
  {
    set: "potential-bugs",
    id: "UnnecessaryNotNullCheck",
    active: false,
    severity: "Error",
    className: "dev.detekt.rules.potentialbugs.UnnecessaryNotNullCheck",
    requiresAnalysisApi: true,
  },
  {
    set: "potential-bugs",
    id: "UnnecessaryNotNullOperator",
    active: true,
    severity: "Error",
    className: "dev.detekt.rules.potentialbugs.UnnecessaryNotNullOperator",
    requiresAnalysisApi: true,
  },
  {
    set: "potential-bugs",
    id: "UnnecessarySafeCall",
    active: true,
    severity: "Error",
    className: "dev.detekt.rules.potentialbugs.UnnecessarySafeCall",
    requiresAnalysisApi: true,
  },
  {
    set: "potential-bugs",
    id: "UnreachableCatchBlock",
    active: true,
    severity: "Error",
    className: "dev.detekt.rules.potentialbugs.UnreachableCatchBlock",
    requiresAnalysisApi: true,
  },
  {
    set: "potential-bugs",
    id: "UnreachableCode",
    active: true,
    severity: "Error",
    className: "dev.detekt.rules.potentialbugs.UnreachableCode",
    requiresAnalysisApi: true,
  },
  {
    set: "potential-bugs",
    id: "UnsafeCallOnNullableType",
    active: true,
    severity: "Error",
    className: "dev.detekt.rules.potentialbugs.UnsafeCallOnNullableType",
    requiresAnalysisApi: true,
  },
  {
    set: "potential-bugs",
    id: "UnsafeCast",
    active: true,
    severity: "Error",
    className: "dev.detekt.rules.potentialbugs.UnsafeCast",
    requiresAnalysisApi: true,
  },
  {
    set: "potential-bugs",
    id: "UnusedUnaryOperator",
    active: true,
    severity: "Error",
    className: "dev.detekt.rules.potentialbugs.UnusedUnaryOperator",
    requiresAnalysisApi: true,
  },
  {
    set: "potential-bugs",
    id: "UselessPostfixExpression",
    active: true,
    severity: "Error",
    className: "dev.detekt.rules.potentialbugs.UselessPostfixExpression",
    requiresAnalysisApi: false,
  },
  {
    set: "potential-bugs",
    id: "WrongEqualsTypeParameter",
    active: true,
    severity: "Error",
    className: "dev.detekt.rules.potentialbugs.WrongEqualsTypeParameter",
    requiresAnalysisApi: false,
  },
  {
    set: "exceptions",
    id: "ErrorUsageWithThrowable",
    active: false,
    severity: "Error",
    className: "dev.detekt.rules.exceptions.ErrorUsageWithThrowable",
    requiresAnalysisApi: true,
  },
  {
    set: "exceptions",
    id: "ExceptionRaisedInUnexpectedLocation",
    active: true,
    severity: "Error",
    className:
      "dev.detekt.rules.exceptions.ExceptionRaisedInUnexpectedLocation",
    requiresAnalysisApi: false,
  },
  {
    set: "exceptions",
    id: "InstanceOfCheckForException",
    active: true,
    severity: "Error",
    className: "dev.detekt.rules.exceptions.InstanceOfCheckForException",
    requiresAnalysisApi: true,
  },
  {
    set: "exceptions",
    id: "NotImplementedDeclaration",
    active: false,
    severity: "Error",
    className: "dev.detekt.rules.exceptions.NotImplementedDeclaration",
    requiresAnalysisApi: false,
  },
  {
    set: "exceptions",
    id: "ObjectExtendsThrowable",
    active: false,
    severity: "Error",
    className: "dev.detekt.rules.exceptions.ObjectExtendsThrowable",
    requiresAnalysisApi: true,
  },
  {
    set: "exceptions",
    id: "PrintStackTrace",
    active: true,
    severity: "Error",
    className: "dev.detekt.rules.exceptions.PrintStackTrace",
    requiresAnalysisApi: false,
  },
  {
    set: "exceptions",
    id: "RethrowCaughtException",
    active: true,
    severity: "Error",
    className: "dev.detekt.rules.exceptions.RethrowCaughtException",
    requiresAnalysisApi: false,
  },
  {
    set: "exceptions",
    id: "ReturnFromFinally",
    active: true,
    severity: "Error",
    className: "dev.detekt.rules.exceptions.ReturnFromFinally",
    requiresAnalysisApi: true,
  },
  {
    set: "exceptions",
    id: "SwallowedException",
    active: true,
    severity: "Error",
    className: "dev.detekt.rules.exceptions.SwallowedException",
    requiresAnalysisApi: false,
  },
  {
    set: "exceptions",
    id: "ThrowingExceptionFromFinally",
    active: true,
    severity: "Error",
    className: "dev.detekt.rules.exceptions.ThrowingExceptionFromFinally",
    requiresAnalysisApi: false,
  },
  {
    set: "exceptions",
    id: "ThrowingExceptionInMain",
    active: false,
    severity: "Error",
    className: "dev.detekt.rules.exceptions.ThrowingExceptionInMain",
    requiresAnalysisApi: false,
  },
  {
    set: "exceptions",
    id: "ThrowingExceptionsWithoutMessageOrCause",
    active: true,
    severity: "Error",
    className:
      "dev.detekt.rules.exceptions.ThrowingExceptionsWithoutMessageOrCause",
    requiresAnalysisApi: false,
  },
  {
    set: "exceptions",
    id: "ThrowingNewInstanceOfSameException",
    active: true,
    severity: "Error",
    className: "dev.detekt.rules.exceptions.ThrowingNewInstanceOfSameException",
    requiresAnalysisApi: false,
  },
  {
    set: "exceptions",
    id: "TooGenericExceptionCaught",
    active: true,
    severity: "Error",
    className: "dev.detekt.rules.exceptions.TooGenericExceptionCaught",
    requiresAnalysisApi: false,
  },
  {
    set: "exceptions",
    id: "TooGenericExceptionThrown",
    active: true,
    severity: "Error",
    className: "dev.detekt.rules.exceptions.TooGenericExceptionThrown",
    requiresAnalysisApi: false,
  },
  {
    set: "naming",
    id: "BooleanPropertyNaming",
    active: false,
    severity: "Error",
    className: "dev.detekt.rules.naming.BooleanPropertyNaming",
    requiresAnalysisApi: true,
  },
  {
    set: "naming",
    id: "ClassNaming",
    active: true,
    severity: "Error",
    className: "dev.detekt.rules.naming.ClassNaming",
    requiresAnalysisApi: false,
  },
  {
    set: "naming",
    id: "ConstructorParameterNaming",
    active: true,
    severity: "Error",
    className: "dev.detekt.rules.naming.ConstructorParameterNaming",
    requiresAnalysisApi: false,
  },
  {
    set: "naming",
    id: "EnumNaming",
    active: true,
    severity: "Error",
    className: "dev.detekt.rules.naming.EnumNaming",
    requiresAnalysisApi: false,
  },
  {
    set: "naming",
    id: "ForbiddenClassName",
    active: false,
    severity: "Error",
    className: "dev.detekt.rules.naming.ForbiddenClassName",
    requiresAnalysisApi: false,
  },
  {
    set: "naming",
    id: "FunctionNameMaxLength",
    active: false,
    severity: "Error",
    className: "dev.detekt.rules.naming.FunctionNameMaxLength",
    requiresAnalysisApi: false,
  },
  {
    set: "naming",
    id: "FunctionNameMinLength",
    active: false,
    severity: "Error",
    className: "dev.detekt.rules.naming.FunctionNameMinLength",
    requiresAnalysisApi: false,
  },
  {
    set: "naming",
    id: "FunctionNaming",
    active: true,
    severity: "Error",
    className: "dev.detekt.rules.naming.FunctionNaming",
    requiresAnalysisApi: false,
  },
  {
    set: "naming",
    id: "FunctionParameterNaming",
    active: true,
    severity: "Error",
    className: "dev.detekt.rules.naming.FunctionParameterNaming",
    requiresAnalysisApi: false,
  },
  {
    set: "naming",
    id: "InvalidPackageDeclaration",
    active: true,
    severity: "Error",
    className: "dev.detekt.rules.naming.InvalidPackageDeclaration",
    requiresAnalysisApi: false,
  },
  {
    set: "naming",
    id: "LambdaParameterNaming",
    active: false,
    severity: "Error",
    className: "dev.detekt.rules.naming.LambdaParameterNaming",
    requiresAnalysisApi: false,
  },
  {
    set: "naming",
    id: "MatchingDeclarationName",
    active: true,
    severity: "Error",
    className: "dev.detekt.rules.naming.MatchingDeclarationName",
    requiresAnalysisApi: false,
  },
  {
    set: "naming",
    id: "MemberNameEqualsClassName",
    active: true,
    severity: "Error",
    className: "dev.detekt.rules.naming.MemberNameEqualsClassName",
    requiresAnalysisApi: true,
  },
  {
    set: "naming",
    id: "NoNameShadowing",
    active: true,
    severity: "Error",
    className: "dev.detekt.rules.naming.NoNameShadowing",
    requiresAnalysisApi: true,
  },
  {
    set: "naming",
    id: "NonBooleanPropertyPrefixedWithIs",
    active: false,
    severity: "Error",
    className: "dev.detekt.rules.naming.NonBooleanPropertyPrefixedWithIs",
    requiresAnalysisApi: true,
  },
  {
    set: "naming",
    id: "ObjectPropertyNaming",
    active: true,
    severity: "Error",
    className: "dev.detekt.rules.naming.ObjectPropertyNaming",
    requiresAnalysisApi: false,
  },
  {
    set: "naming",
    id: "PackageNaming",
    active: true,
    severity: "Error",
    className: "dev.detekt.rules.naming.PackageNaming",
    requiresAnalysisApi: false,
  },
  {
    set: "naming",
    id: "TopLevelPropertyNaming",
    active: true,
    severity: "Error",
    className: "dev.detekt.rules.naming.TopLevelPropertyNaming",
    requiresAnalysisApi: false,
  },
  {
    set: "naming",
    id: "VariableMaxLength",
    active: false,
    severity: "Error",
    className: "dev.detekt.rules.naming.VariableMaxLength",
    requiresAnalysisApi: false,
  },
  {
    set: "naming",
    id: "VariableMinLength",
    active: false,
    severity: "Error",
    className: "dev.detekt.rules.naming.VariableMinLength",
    requiresAnalysisApi: false,
  },
  {
    set: "naming",
    id: "VariableNaming",
    active: true,
    severity: "Error",
    className: "dev.detekt.rules.naming.VariableNaming",
    requiresAnalysisApi: false,
  },
  {
    set: "performance",
    id: "ArrayPrimitive",
    active: true,
    severity: "Error",
    className: "dev.detekt.rules.performance.ArrayPrimitive",
    requiresAnalysisApi: true,
  },
  {
    set: "performance",
    id: "CouldBeSequence",
    active: false,
    severity: "Error",
    className: "dev.detekt.rules.performance.CouldBeSequence",
    requiresAnalysisApi: true,
  },
  {
    set: "performance",
    id: "ForEachOnRange",
    active: true,
    severity: "Error",
    className: "dev.detekt.rules.performance.ForEachOnRange",
    requiresAnalysisApi: false,
  },
  {
    set: "performance",
    id: "SpreadOperator",
    active: true,
    severity: "Error",
    className: "dev.detekt.rules.performance.SpreadOperator",
    requiresAnalysisApi: true,
  },
  {
    set: "performance",
    id: "UnnecessaryInitOnArray",
    active: false,
    severity: "Error",
    className: "dev.detekt.rules.performance.UnnecessaryInitOnArray",
    requiresAnalysisApi: false,
  },
  {
    set: "performance",
    id: "UnnecessaryPartOfBinaryExpression",
    active: false,
    severity: "Error",
    className: "dev.detekt.rules.performance.UnnecessaryPartOfBinaryExpression",
    requiresAnalysisApi: false,
  },
  {
    set: "performance",
    id: "UnnecessaryTemporaryInstantiation",
    active: true,
    severity: "Error",
    className: "dev.detekt.rules.performance.UnnecessaryTemporaryInstantiation",
    requiresAnalysisApi: false,
  },
  {
    set: "performance",
    id: "UnnecessaryTypeCasting",
    active: false,
    severity: "Error",
    className: "dev.detekt.rules.performance.UnnecessaryTypeCasting",
    requiresAnalysisApi: false,
  },
  {
    set: "style",
    id: "AbstractClassCanBeConcreteClass",
    active: true,
    severity: "Error",
    className: "dev.detekt.rules.style.AbstractClassCanBeConcreteClass",
    requiresAnalysisApi: true,
  },
  {
    set: "style",
    id: "AbstractClassCanBeInterface",
    active: true,
    severity: "Error",
    className: "dev.detekt.rules.style.AbstractClassCanBeInterface",
    requiresAnalysisApi: true,
  },
  {
    set: "style",
    id: "AlsoCouldBeApply",
    active: false,
    severity: "Error",
    className: "dev.detekt.rules.style.AlsoCouldBeApply",
    requiresAnalysisApi: false,
  },
  {
    set: "style",
    id: "BracesOnIfStatements",
    active: false,
    severity: "Error",
    className: "dev.detekt.rules.style.BracesOnIfStatements",
    requiresAnalysisApi: false,
  },
  {
    set: "style",
    id: "BracesOnWhenStatements",
    active: false,
    severity: "Error",
    className: "dev.detekt.rules.style.BracesOnWhenStatements",
    requiresAnalysisApi: false,
  },
  {
    set: "style",
    id: "CanBeNonNullable",
    active: false,
    severity: "Error",
    className: "dev.detekt.rules.style.CanBeNonNullable",
    requiresAnalysisApi: true,
  },
  {
    set: "style",
    id: "CascadingCallWrapping",
    active: false,
    severity: "Error",
    className: "dev.detekt.rules.style.CascadingCallWrapping",
    requiresAnalysisApi: false,
  },
  {
    set: "style",
    id: "ClassOrdering",
    active: false,
    severity: "Error",
    className: "dev.detekt.rules.style.ClassOrdering",
    requiresAnalysisApi: false,
  },
  {
    set: "style",
    id: "CollapsibleIfStatements",
    active: false,
    severity: "Error",
    className: "dev.detekt.rules.style.CollapsibleIfStatements",
    requiresAnalysisApi: false,
  },
  {
    set: "style",
    id: "DataClassContainsFunctions",
    active: false,
    severity: "Error",
    className: "dev.detekt.rules.style.DataClassContainsFunctions",
    requiresAnalysisApi: false,
  },
  {
    set: "style",
    id: "DataClassShouldBeImmutable",
    active: false,
    severity: "Error",
    className: "dev.detekt.rules.style.DataClassShouldBeImmutable",
    requiresAnalysisApi: false,
  },
  {
    set: "style",
    id: "DestructuringDeclarationWithTooManyEntries",
    active: true,
    severity: "Error",
    className:
      "dev.detekt.rules.style.DestructuringDeclarationWithTooManyEntries",
    requiresAnalysisApi: false,
  },
  {
    set: "style",
    id: "DoubleNegativeExpression",
    active: false,
    severity: "Error",
    className: "dev.detekt.rules.style.DoubleNegativeExpression",
    requiresAnalysisApi: true,
  },
  {
    set: "style",
    id: "DoubleNegativeLambda",
    active: false,
    severity: "Error",
    className: "dev.detekt.rules.style.DoubleNegativeLambda",
    requiresAnalysisApi: false,
  },
  {
    set: "style",
    id: "EqualsNullCall",
    active: true,
    severity: "Error",
    className: "dev.detekt.rules.style.EqualsNullCall",
    requiresAnalysisApi: false,
  },
  {
    set: "style",
    id: "EqualsOnSignatureLine",
    active: false,
    severity: "Error",
    className: "dev.detekt.rules.style.EqualsOnSignatureLine",
    requiresAnalysisApi: false,
  },
  {
    set: "style",
    id: "ExplicitCollectionElementAccessMethod",
    active: false,
    severity: "Error",
    className: "dev.detekt.rules.style.ExplicitCollectionElementAccessMethod",
    requiresAnalysisApi: true,
  },
  {
    set: "style",
    id: "ExplicitItLambdaMultipleParameters",
    active: true,
    severity: "Error",
    className: "dev.detekt.rules.style.ExplicitItLambdaMultipleParameters",
    requiresAnalysisApi: false,
  },
  {
    set: "style",
    id: "ExplicitItLambdaParameter",
    active: true,
    severity: "Error",
    className: "dev.detekt.rules.style.ExplicitItLambdaParameter",
    requiresAnalysisApi: false,
  },
  {
    set: "style",
    id: "ExpressionBodySyntax",
    active: false,
    severity: "Error",
    className: "dev.detekt.rules.style.ExpressionBodySyntax",
    requiresAnalysisApi: false,
  },
  {
    set: "style",
    id: "ForbiddenAnnotation",
    active: false,
    severity: "Error",
    className: "dev.detekt.rules.style.ForbiddenAnnotation",
    requiresAnalysisApi: true,
  },
  {
    set: "style",
    id: "ForbiddenComment",
    active: true,
    severity: "Error",
    className: "dev.detekt.rules.style.ForbiddenComment",
    requiresAnalysisApi: false,
  },
  {
    set: "style",
    id: "ForbiddenImport",
    active: false,
    severity: "Error",
    className: "dev.detekt.rules.style.ForbiddenImport",
    requiresAnalysisApi: false,
  },
  {
    set: "style",
    id: "ForbiddenMethodCall",
    active: false,
    severity: "Error",
    className: "dev.detekt.rules.style.ForbiddenMethodCall",
    requiresAnalysisApi: true,
  },
  {
    set: "style",
    id: "ForbiddenNamedParam",
    active: false,
    severity: "Error",
    className: "dev.detekt.rules.style.ForbiddenNamedParam",
    requiresAnalysisApi: true,
  },
  {
    set: "style",
    id: "ForbiddenOptIn",
    active: false,
    severity: "Error",
    className: "dev.detekt.rules.style.ForbiddenOptIn",
    requiresAnalysisApi: true,
  },
  {
    set: "style",
    id: "ForbiddenSuppress",
    active: false,
    severity: "Error",
    className: "dev.detekt.rules.style.ForbiddenSuppress",
    requiresAnalysisApi: false,
  },
  {
    set: "style",
    id: "ForbiddenVoid",
    active: true,
    severity: "Error",
    className: "dev.detekt.rules.style.ForbiddenVoid",
    requiresAnalysisApi: true,
  },
  {
    set: "style",
    id: "FunctionOnlyReturningConstant",
    active: true,
    severity: "Error",
    className: "dev.detekt.rules.style.FunctionOnlyReturningConstant",
    requiresAnalysisApi: false,
  },
  {
    set: "style",
    id: "LoopWithTooManyJumpStatements",
    active: true,
    severity: "Error",
    className: "dev.detekt.rules.style.LoopWithTooManyJumpStatements",
    requiresAnalysisApi: false,
  },
  {
    set: "style",
    id: "MagicNumber",
    active: true,
    severity: "Error",
    className: "dev.detekt.rules.style.MagicNumber",
    requiresAnalysisApi: false,
  },
  {
    set: "style",
    id: "MandatoryBracesLoops",
    active: false,
    severity: "Error",
    className: "dev.detekt.rules.style.optional.MandatoryBracesLoops",
    requiresAnalysisApi: false,
  },
  {
    set: "style",
    id: "MaxChainedCallsOnSameLine",
    active: false,
    severity: "Error",
    className: "dev.detekt.rules.style.MaxChainedCallsOnSameLine",
    requiresAnalysisApi: true,
  },
  {
    set: "style",
    id: "MaxLineLength",
    active: true,
    severity: "Error",
    className: "dev.detekt.rules.style.MaxLineLength",
    requiresAnalysisApi: false,
  },
  {
    set: "style",
    id: "MayBeConstant",
    active: true,
    severity: "Error",
    className: "dev.detekt.rules.style.MayBeConstant",
    requiresAnalysisApi: false,
  },
  {
    set: "style",
    id: "ModifierOrder",
    active: true,
    severity: "Error",
    className: "dev.detekt.rules.style.ModifierOrder",
    requiresAnalysisApi: false,
  },
  {
    set: "style",
    id: "MultilineLambdaItParameter",
    active: false,
    severity: "Error",
    className: "dev.detekt.rules.style.MultilineLambdaItParameter",
    requiresAnalysisApi: true,
  },
  {
    set: "style",
    id: "MultilineRawStringIndentation",
    active: false,
    severity: "Error",
    className: "dev.detekt.rules.style.MultilineRawStringIndentation",
    requiresAnalysisApi: false,
  },
  {
    set: "style",
    id: "NestedClassesVisibility",
    active: true,
    severity: "Error",
    className: "dev.detekt.rules.style.NestedClassesVisibility",
    requiresAnalysisApi: false,
  },
  {
    set: "style",
    id: "NewLineAtEndOfFile",
    active: true,
    severity: "Error",
    className: "dev.detekt.rules.style.NewLineAtEndOfFile",
    requiresAnalysisApi: false,
  },
  {
    set: "style",
    id: "NoTabs",
    active: false,
    severity: "Error",
    className: "dev.detekt.rules.style.NoTabs",
    requiresAnalysisApi: false,
  },
  {
    set: "style",
    id: "NullableBooleanCheck",
    active: false,
    severity: "Error",
    className: "dev.detekt.rules.style.NullableBooleanCheck",
    requiresAnalysisApi: true,
  },
  {
    set: "style",
    id: "ObjectLiteralToLambda",
    active: true,
    severity: "Error",
    className: "dev.detekt.rules.style.ObjectLiteralToLambda",
    requiresAnalysisApi: true,
  },
  {
    set: "style",
    id: "OptionalAbstractKeyword",
    active: true,
    severity: "Error",
    className: "dev.detekt.rules.style.OptionalAbstractKeyword",
    requiresAnalysisApi: false,
  },
  {
    set: "style",
    id: "OptionalUnit",
    active: false,
    severity: "Error",
    className: "dev.detekt.rules.style.optional.OptionalUnit",
    requiresAnalysisApi: true,
  },
  {
    set: "style",
    id: "ProtectedMemberInFinalClass",
    active: true,
    severity: "Error",
    className: "dev.detekt.rules.style.ProtectedMemberInFinalClass",
    requiresAnalysisApi: false,
  },
  {
    set: "style",
    id: "RangeUntilInsteadOfRangeTo",
    active: false,
    severity: "Error",
    className: "dev.detekt.rules.style.RangeUntilInsteadOfRangeTo",
    requiresAnalysisApi: false,
  },
  {
    set: "style",
    id: "RedundantConstructorKeyword",
    active: false,
    severity: "Error",
    className: "dev.detekt.rules.style.RedundantConstructorKeyword",
    requiresAnalysisApi: false,
  },
  {
    set: "style",
    id: "RedundantExplicitType",
    active: false,
    severity: "Error",
    className: "dev.detekt.rules.style.RedundantExplicitType",
    requiresAnalysisApi: true,
  },
  {
    set: "style",
    id: "RedundantHigherOrderMapUsage",
    active: true,
    severity: "Error",
    className: "dev.detekt.rules.style.RedundantHigherOrderMapUsage",
    requiresAnalysisApi: true,
  },
  {
    set: "style",
    id: "RedundantVisibilityModifier",
    active: false,
    severity: "Error",
    className: "dev.detekt.rules.style.RedundantVisibilityModifier",
    requiresAnalysisApi: false,
  },
  {
    set: "style",
    id: "ReturnCount",
    active: true,
    severity: "Error",
    className: "dev.detekt.rules.style.ReturnCount",
    requiresAnalysisApi: false,
  },
  {
    set: "style",
    id: "SafeCast",
    active: true,
    severity: "Error",
    className: "dev.detekt.rules.style.SafeCast",
    requiresAnalysisApi: false,
  },
  {
    set: "style",
    id: "SerialVersionUIDInSerializableClass",
    active: true,
    severity: "Error",
    className: "dev.detekt.rules.style.SerialVersionUIDInSerializableClass",
    requiresAnalysisApi: false,
  },
  {
    set: "style",
    id: "SpacingAfterPackageAndImports",
    active: false,
    severity: "Error",
    className: "dev.detekt.rules.style.SpacingAfterPackageAndImports",
    requiresAnalysisApi: false,
  },
  {
    set: "style",
    id: "StringShouldBeRawString",
    active: false,
    severity: "Error",
    className: "dev.detekt.rules.style.StringShouldBeRawString",
    requiresAnalysisApi: false,
  },
  {
    set: "style",
    id: "ThrowsCount",
    active: true,
    severity: "Error",
    className: "dev.detekt.rules.style.ThrowsCount",
    requiresAnalysisApi: false,
  },
  {
    set: "style",
    id: "TrailingWhitespace",
    active: false,
    severity: "Error",
    className: "dev.detekt.rules.style.TrailingWhitespace",
    requiresAnalysisApi: false,
  },
  {
    set: "style",
    id: "TrimMultilineRawString",
    active: false,
    severity: "Error",
    className: "dev.detekt.rules.style.TrimMultilineRawString",
    requiresAnalysisApi: false,
  },
  {
    set: "style",
    id: "UnderscoresInNumericLiterals",
    active: false,
    severity: "Error",
    className: "dev.detekt.rules.style.UnderscoresInNumericLiterals",
    requiresAnalysisApi: false,
  },
  {
    set: "style",
    id: "UnnecessaryAny",
    active: false,
    severity: "Error",
    className: "dev.detekt.rules.style.UnnecessaryAny",
    requiresAnalysisApi: true,
  },
  {
    set: "style",
    id: "UnnecessaryApply",
    active: true,
    severity: "Error",
    className: "dev.detekt.rules.style.UnnecessaryApply",
    requiresAnalysisApi: true,
  },
  {
    set: "style",
    id: "UnnecessaryBackticks",
    active: false,
    severity: "Error",
    className: "dev.detekt.rules.style.UnnecessaryBackticks",
    requiresAnalysisApi: false,
  },
  {
    set: "style",
    id: "UnnecessaryBracesAroundTrailingLambda",
    active: false,
    severity: "Error",
    className:
      "dev.detekt.rules.style.movelambdaout.UnnecessaryBracesAroundTrailingLambda",
    requiresAnalysisApi: true,
  },
  {
    set: "style",
    id: "UnnecessaryFilter",
    active: true,
    severity: "Error",
    className: "dev.detekt.rules.style.UnnecessaryFilter",
    requiresAnalysisApi: true,
  },
  {
    set: "style",
    id: "UnnecessaryFullyQualifiedName",
    active: false,
    severity: "Error",
    className: "dev.detekt.rules.style.UnnecessaryFullyQualifiedName",
    requiresAnalysisApi: true,
  },
  {
    set: "style",
    id: "UnnecessaryInheritance",
    active: true,
    severity: "Error",
    className: "dev.detekt.rules.style.UnnecessaryInheritance",
    requiresAnalysisApi: false,
  },
  {
    set: "style",
    id: "UnnecessaryInnerClass",
    active: false,
    severity: "Error",
    className: "dev.detekt.rules.style.UnnecessaryInnerClass",
    requiresAnalysisApi: true,
  },
  {
    set: "style",
    id: "UnnecessaryLet",
    active: false,
    severity: "Error",
    className: "dev.detekt.rules.style.UnnecessaryLet",
    requiresAnalysisApi: true,
  },
  {
    set: "style",
    id: "UnnecessaryParentheses",
    active: false,
    severity: "Error",
    className: "dev.detekt.rules.style.UnnecessaryParentheses",
    requiresAnalysisApi: false,
  },
  {
    set: "style",
    id: "UnnecessaryReversed",
    active: false,
    severity: "Error",
    className: "dev.detekt.rules.style.UnnecessaryReversed",
    requiresAnalysisApi: true,
  },
  {
    set: "style",
    id: "UnusedImport",
    active: false,
    severity: "Error",
    className: "dev.detekt.rules.style.UnusedImport",
    requiresAnalysisApi: true,
  },
  {
    set: "style",
    id: "UnusedParameter",
    active: true,
    severity: "Error",
    className: "dev.detekt.rules.style.UnusedParameter",
    requiresAnalysisApi: false,
  },
  {
    set: "style",
    id: "UnusedPrivateClass",
    active: true,
    severity: "Error",
    className: "dev.detekt.rules.style.UnusedPrivateClass",
    requiresAnalysisApi: false,
  },
  {
    set: "style",
    id: "UnusedPrivateFunction",
    active: true,
    severity: "Error",
    className: "dev.detekt.rules.style.UnusedPrivateFunction",
    requiresAnalysisApi: true,
  },
  {
    set: "style",
    id: "UnusedPrivateProperty",
    active: true,
    severity: "Error",
    className: "dev.detekt.rules.style.UnusedPrivateProperty",
    requiresAnalysisApi: true,
  },
  {
    set: "style",
    id: "UnusedVariable",
    active: true,
    severity: "Error",
    className: "dev.detekt.rules.style.UnusedVariable",
    requiresAnalysisApi: true,
  },
  {
    set: "style",
    id: "UseAnyOrNoneInsteadOfFind",
    active: true,
    severity: "Error",
    className: "dev.detekt.rules.style.UseAnyOrNoneInsteadOfFind",
    requiresAnalysisApi: true,
  },
  {
    set: "style",
    id: "UseArrayLiteralsInAnnotations",
    active: true,
    severity: "Error",
    className: "dev.detekt.rules.style.UseArrayLiteralsInAnnotations",
    requiresAnalysisApi: false,
  },
  {
    set: "style",
    id: "UseCheckNotNull",
    active: true,
    severity: "Error",
    className: "dev.detekt.rules.style.UseCheckNotNull",
    requiresAnalysisApi: true,
  },
  {
    set: "style",
    id: "UseCheckOrError",
    active: true,
    severity: "Error",
    className: "dev.detekt.rules.style.UseCheckOrError",
    requiresAnalysisApi: true,
  },
  {
    set: "style",
    id: "UseDataClass",
    active: false,
    severity: "Error",
    className: "dev.detekt.rules.style.UseDataClass",
    requiresAnalysisApi: true,
  },
  {
    set: "style",
    id: "UseEmptyCounterpart",
    active: false,
    severity: "Error",
    className: "dev.detekt.rules.style.UseEmptyCounterpart",
    requiresAnalysisApi: true,
  },
  {
    set: "style",
    id: "UseIfEmptyOrIfBlank",
    active: false,
    severity: "Error",
    className: "dev.detekt.rules.style.UseIfEmptyOrIfBlank",
    requiresAnalysisApi: true,
  },
  {
    set: "style",
    id: "UseIfInsteadOfWhen",
    active: false,
    severity: "Error",
    className: "dev.detekt.rules.style.UseIfInsteadOfWhen",
    requiresAnalysisApi: false,
  },
  {
    set: "style",
    id: "UseIsNullOrEmpty",
    active: true,
    severity: "Error",
    className: "dev.detekt.rules.style.UseIsNullOrEmpty",
    requiresAnalysisApi: true,
  },
  {
    set: "style",
    id: "UseLet",
    active: false,
    severity: "Error",
    className: "dev.detekt.rules.style.UseLet",
    requiresAnalysisApi: false,
  },
  {
    set: "style",
    id: "UseOrEmpty",
    active: true,
    severity: "Error",
    className: "dev.detekt.rules.style.UseOrEmpty",
    requiresAnalysisApi: true,
  },
  {
    set: "style",
    id: "UseRequire",
    active: true,
    severity: "Error",
    className: "dev.detekt.rules.style.UseRequire",
    requiresAnalysisApi: true,
  },
  {
    set: "style",
    id: "UseRequireNotNull",
    active: true,
    severity: "Error",
    className: "dev.detekt.rules.style.UseRequireNotNull",
    requiresAnalysisApi: true,
  },
  {
    set: "style",
    id: "UseSumOfInsteadOfFlatMapSize",
    active: false,
    severity: "Error",
    className: "dev.detekt.rules.style.UseSumOfInsteadOfFlatMapSize",
    requiresAnalysisApi: true,
  },
  {
    set: "style",
    id: "UselessCallOnNotNull",
    active: true,
    severity: "Error",
    className: "dev.detekt.rules.style.UselessCallOnNotNull",
    requiresAnalysisApi: true,
  },
  {
    set: "style",
    id: "UtilityClassWithPublicConstructor",
    active: true,
    severity: "Error",
    className: "dev.detekt.rules.style.UtilityClassWithPublicConstructor",
    requiresAnalysisApi: false,
  },
  {
    set: "style",
    id: "VarCouldBeVal",
    active: true,
    severity: "Error",
    className: "dev.detekt.rules.style.VarCouldBeVal",
    requiresAnalysisApi: true,
  },
  {
    set: "style",
    id: "WildcardImport",
    active: true,
    severity: "Error",
    className: "dev.detekt.rules.style.WildcardImport",
    requiresAnalysisApi: false,
  },
] as const;
export const detektFullSdkModules = [
  "java.base",
  "java.compiler",
  "java.datatransfer",
  "java.desktop",
  "java.instrument",
  "java.logging",
  "java.management",
  "java.management.rmi",
  "java.naming",
  "java.net.http",
  "java.prefs",
  "java.rmi",
  "java.scripting",
  "java.se",
  "java.security.jgss",
  "java.security.sasl",
  "java.smartcardio",
  "java.sql",
  "java.sql.rowset",
  "java.transaction.xa",
  "java.xml",
  "java.xml.crypto",
  "jdk.accessibility",
  "jdk.attach",
  "jdk.charsets",
  "jdk.compiler",
  "jdk.crypto.cryptoki",
  "jdk.crypto.ec",
  "jdk.dynalink",
  "jdk.editpad",
  "jdk.graal.compiler",
  "jdk.graal.compiler.management",
  "jdk.hotspot.agent",
  "jdk.httpserver",
  "jdk.incubator.vector",
  "jdk.internal.ed",
  "jdk.internal.jvmstat",
  "jdk.internal.le",
  "jdk.internal.md",
  "jdk.internal.opt",
  "jdk.internal.vm.ci",
  "jdk.jartool",
  "jdk.javadoc",
  "jdk.jcmd",
  "jdk.jconsole",
  "jdk.jdeps",
  "jdk.jdi",
  "jdk.jdwp.agent",
  "jdk.jfr",
  "jdk.jlink",
  "jdk.jpackage",
  "jdk.jshell",
  "jdk.jsobject",
  "jdk.jstatd",
  "jdk.localedata",
  "jdk.management",
  "jdk.management.agent",
  "jdk.management.jfr",
  "jdk.naming.dns",
  "jdk.naming.rmi",
  "jdk.net",
  "jdk.nio.mapmode",
  "jdk.sctp",
  "jdk.security.auth",
  "jdk.security.jgss",
  "jdk.unsupported",
  "jdk.unsupported.desktop",
  "jdk.xml.dom",
  "jdk.zipfs",
] as const;
