export const detektArtifacts = {
  version: "2.0.0-alpha.6",
  jarBytes: 84733979,
  jarSha256: "d46ca62ea4d62769b5d5c3ba94d49fa9b80ba11c7dba74ddb6df7fcc2c19c5fd",
  defaultConfigBytes: 24093,
  defaultConfigSha256:
    "6d8ec7aaaa945c5caf1d4924a26faf7b94ed36f93e4b329e45a36a4996441c9d",
  configurationSha256:
    "353af7173c4b71c376a201a9caafded9ab3a67b92e98612fd543705b00509480",
  configurationBytes: 21019,
  ruleSets: [
    "comments",
    "complexity",
    "coroutines",
    "empty-blocks",
    "exceptions",
    "naming",
    "performance",
    "potential-bugs",
    "style",
  ],
  rules: [
    {
      set: "complexity",
      id: "CognitiveComplexMethod",
      active: false,
      severity: "Error",
    },
    {
      set: "complexity",
      id: "ComplexCondition",
      active: true,
      severity: "Error",
    },
    {
      set: "complexity",
      id: "ComplexInterface",
      active: false,
      severity: "Error",
    },
    {
      set: "complexity",
      id: "CyclomaticComplexMethod",
      active: true,
      severity: "Error",
    },
    {
      set: "complexity",
      id: "LabeledExpression",
      active: false,
      severity: "Error",
    },
    {
      set: "complexity",
      id: "LargeClass",
      active: true,
      severity: "Error",
    },
    {
      set: "complexity",
      id: "LongMethod",
      active: true,
      severity: "Error",
    },
    {
      set: "complexity",
      id: "LongParameterList",
      active: false,
      severity: "Error",
    },
    {
      set: "complexity",
      id: "MethodOverloading",
      active: false,
      severity: "Error",
    },
    {
      set: "complexity",
      id: "NamedArguments",
      active: false,
      severity: "Error",
    },
    {
      set: "complexity",
      id: "NestedBlockDepth",
      active: true,
      severity: "Error",
    },
    {
      set: "complexity",
      id: "NestedScopeFunctions",
      active: false,
      severity: "Error",
    },
    {
      set: "complexity",
      id: "ReplaceSafeCallChainWithRun",
      active: false,
      severity: "Error",
    },
    {
      set: "complexity",
      id: "StringLiteralDuplication",
      active: false,
      severity: "Error",
    },
    {
      set: "complexity",
      id: "TooManyFunctions",
      active: true,
      severity: "Error",
    },
    {
      set: "coroutines",
      id: "CoroutineLaunchedInTestWithoutRunTest",
      active: false,
      severity: "Error",
    },
    {
      set: "coroutines",
      id: "GlobalCoroutineUsage",
      active: false,
      severity: "Error",
    },
    {
      set: "coroutines",
      id: "InjectDispatcher",
      active: false,
      severity: "Error",
    },
    {
      set: "coroutines",
      id: "RedundantSuspendModifier",
      active: false,
      severity: "Error",
    },
    {
      set: "coroutines",
      id: "SleepInsteadOfDelay",
      active: false,
      severity: "Error",
    },
    {
      set: "coroutines",
      id: "SuspendFunInFinallySection",
      active: false,
      severity: "Error",
    },
    {
      set: "coroutines",
      id: "SuspendFunSwallowedCancellation",
      active: false,
      severity: "Error",
    },
    {
      set: "coroutines",
      id: "SuspendFunWithCoroutineScopeReceiver",
      active: false,
      severity: "Error",
    },
    {
      set: "coroutines",
      id: "SuspendFunWithFlowReturnType",
      active: false,
      severity: "Error",
    },
    {
      set: "comments",
      id: "AbsentOrWrongFileLicense",
      active: false,
      severity: "Error",
    },
    {
      set: "comments",
      id: "DeprecatedBlockTag",
      active: false,
      severity: "Error",
    },
    {
      set: "comments",
      id: "DocumentationOverPrivateFunction",
      active: false,
      severity: "Error",
    },
    {
      set: "comments",
      id: "DocumentationOverPrivateProperty",
      active: false,
      severity: "Error",
    },
    {
      set: "comments",
      id: "EndOfSentenceFormat",
      active: false,
      severity: "Error",
    },
    {
      set: "comments",
      id: "KDocReferencesNonPublicProperty",
      active: false,
      severity: "Error",
    },
    {
      set: "comments",
      id: "OutdatedDocumentation",
      active: false,
      severity: "Error",
    },
    {
      set: "comments",
      id: "UndocumentedPublicClass",
      active: false,
      severity: "Error",
    },
    {
      set: "comments",
      id: "UndocumentedPublicFunction",
      active: false,
      severity: "Error",
    },
    {
      set: "comments",
      id: "UndocumentedPublicProperty",
      active: false,
      severity: "Error",
    },
    {
      set: "empty-blocks",
      id: "EmptyCatchBlock",
      active: true,
      severity: "Error",
    },
    {
      set: "empty-blocks",
      id: "EmptyClassBlock",
      active: true,
      severity: "Error",
    },
    {
      set: "empty-blocks",
      id: "EmptyDefaultConstructor",
      active: true,
      severity: "Error",
    },
    {
      set: "empty-blocks",
      id: "EmptyDoWhileBlock",
      active: true,
      severity: "Error",
    },
    {
      set: "empty-blocks",
      id: "EmptyElseBlock",
      active: true,
      severity: "Error",
    },
    {
      set: "empty-blocks",
      id: "EmptyFinallyBlock",
      active: true,
      severity: "Error",
    },
    {
      set: "empty-blocks",
      id: "EmptyForBlock",
      active: true,
      severity: "Error",
    },
    {
      set: "empty-blocks",
      id: "EmptyFunctionBlock",
      active: true,
      severity: "Error",
    },
    {
      set: "empty-blocks",
      id: "EmptyIfBlock",
      active: true,
      severity: "Error",
    },
    {
      set: "empty-blocks",
      id: "EmptyInitBlock",
      active: true,
      severity: "Error",
    },
    {
      set: "empty-blocks",
      id: "EmptyKotlinFile",
      active: true,
      severity: "Error",
    },
    {
      set: "empty-blocks",
      id: "EmptySecondaryConstructor",
      active: true,
      severity: "Error",
    },
    {
      set: "empty-blocks",
      id: "EmptyTryBlock",
      active: true,
      severity: "Error",
    },
    {
      set: "empty-blocks",
      id: "EmptyWhenBlock",
      active: true,
      severity: "Error",
    },
    {
      set: "empty-blocks",
      id: "EmptyWhileBlock",
      active: true,
      severity: "Error",
    },
    {
      set: "potential-bugs",
      id: "AvoidReferentialEquality",
      active: false,
      severity: "Error",
    },
    {
      set: "potential-bugs",
      id: "CastNullableToNonNullableType",
      active: false,
      severity: "Error",
    },
    {
      set: "potential-bugs",
      id: "CastToNullableType",
      active: false,
      severity: "Error",
    },
    {
      set: "potential-bugs",
      id: "CharArrayToStringCall",
      active: false,
      severity: "Error",
    },
    {
      set: "potential-bugs",
      id: "Deprecation",
      active: false,
      severity: "Error",
    },
    {
      set: "potential-bugs",
      id: "DontDowncastCollectionTypes",
      active: false,
      severity: "Error",
    },
    {
      set: "potential-bugs",
      id: "DoubleMutabilityForCollection",
      active: false,
      severity: "Error",
    },
    {
      set: "potential-bugs",
      id: "ElseCaseInsteadOfExhaustiveWhen",
      active: false,
      severity: "Error",
    },
    {
      set: "potential-bugs",
      id: "EqualsAlwaysReturnsTrueOrFalse",
      active: true,
      severity: "Error",
    },
    {
      set: "potential-bugs",
      id: "EqualsWithHashCodeExist",
      active: true,
      severity: "Error",
    },
    {
      set: "potential-bugs",
      id: "ExitOutsideMain",
      active: false,
      severity: "Error",
    },
    {
      set: "potential-bugs",
      id: "ExplicitGarbageCollectionCall",
      active: true,
      severity: "Error",
    },
    {
      set: "potential-bugs",
      id: "HasPlatformType",
      active: false,
      severity: "Error",
    },
    {
      set: "potential-bugs",
      id: "IgnoredReturnValue",
      active: false,
      severity: "Error",
    },
    {
      set: "potential-bugs",
      id: "ImplicitDefaultLocale",
      active: false,
      severity: "Error",
    },
    {
      set: "potential-bugs",
      id: "ImplicitUnitReturnType",
      active: false,
      severity: "Error",
    },
    {
      set: "potential-bugs",
      id: "InvalidRange",
      active: true,
      severity: "Error",
    },
    {
      set: "potential-bugs",
      id: "IteratorHasNextCallsNextMethod",
      active: true,
      severity: "Error",
    },
    {
      set: "potential-bugs",
      id: "IteratorNotThrowingNoSuchElementException",
      active: true,
      severity: "Error",
    },
    {
      set: "potential-bugs",
      id: "LateinitUsage",
      active: false,
      severity: "Error",
    },
    {
      set: "potential-bugs",
      id: "MapGetWithNotNullAssertionOperator",
      active: false,
      severity: "Error",
    },
    {
      set: "potential-bugs",
      id: "MissingPackageDeclaration",
      active: false,
      severity: "Error",
    },
    {
      set: "potential-bugs",
      id: "MissingSuperCall",
      active: false,
      severity: "Error",
    },
    {
      set: "potential-bugs",
      id: "MissingUseCall",
      active: false,
      severity: "Error",
    },
    {
      set: "potential-bugs",
      id: "NullCheckOnMutableProperty",
      active: false,
      severity: "Error",
    },
    {
      set: "potential-bugs",
      id: "NullableToStringCall",
      active: false,
      severity: "Error",
    },
    {
      set: "potential-bugs",
      id: "PropertyUsedBeforeDeclaration",
      active: false,
      severity: "Error",
    },
    {
      set: "potential-bugs",
      id: "UnconditionalJumpStatementInLoop",
      active: false,
      severity: "Error",
    },
    {
      set: "potential-bugs",
      id: "UnnamedParameterUse",
      active: false,
      severity: "Error",
    },
    {
      set: "potential-bugs",
      id: "UnnecessaryNotNullCheck",
      active: false,
      severity: "Error",
    },
    {
      set: "potential-bugs",
      id: "UnnecessaryNotNullOperator",
      active: false,
      severity: "Error",
    },
    {
      set: "potential-bugs",
      id: "UnnecessarySafeCall",
      active: false,
      severity: "Error",
    },
    {
      set: "potential-bugs",
      id: "UnreachableCatchBlock",
      active: false,
      severity: "Error",
    },
    {
      set: "potential-bugs",
      id: "UnreachableCode",
      active: false,
      severity: "Error",
    },
    {
      set: "potential-bugs",
      id: "UnsafeCallOnNullableType",
      active: false,
      severity: "Error",
    },
    {
      set: "potential-bugs",
      id: "UnsafeCast",
      active: false,
      severity: "Error",
    },
    {
      set: "potential-bugs",
      id: "UnusedUnaryOperator",
      active: false,
      severity: "Error",
    },
    {
      set: "potential-bugs",
      id: "UselessPostfixExpression",
      active: true,
      severity: "Error",
    },
    {
      set: "potential-bugs",
      id: "WrongEqualsTypeParameter",
      active: true,
      severity: "Error",
    },
    {
      set: "exceptions",
      id: "ErrorUsageWithThrowable",
      active: false,
      severity: "Error",
    },
    {
      set: "exceptions",
      id: "ExceptionRaisedInUnexpectedLocation",
      active: true,
      severity: "Error",
    },
    {
      set: "exceptions",
      id: "InstanceOfCheckForException",
      active: false,
      severity: "Error",
    },
    {
      set: "exceptions",
      id: "NotImplementedDeclaration",
      active: false,
      severity: "Error",
    },
    {
      set: "exceptions",
      id: "ObjectExtendsThrowable",
      active: false,
      severity: "Error",
    },
    {
      set: "exceptions",
      id: "PrintStackTrace",
      active: true,
      severity: "Error",
    },
    {
      set: "exceptions",
      id: "RethrowCaughtException",
      active: true,
      severity: "Error",
    },
    {
      set: "exceptions",
      id: "ReturnFromFinally",
      active: false,
      severity: "Error",
    },
    {
      set: "exceptions",
      id: "SwallowedException",
      active: true,
      severity: "Error",
    },
    {
      set: "exceptions",
      id: "ThrowingExceptionFromFinally",
      active: true,
      severity: "Error",
    },
    {
      set: "exceptions",
      id: "ThrowingExceptionInMain",
      active: false,
      severity: "Error",
    },
    {
      set: "exceptions",
      id: "ThrowingExceptionsWithoutMessageOrCause",
      active: true,
      severity: "Error",
    },
    {
      set: "exceptions",
      id: "ThrowingNewInstanceOfSameException",
      active: true,
      severity: "Error",
    },
    {
      set: "exceptions",
      id: "TooGenericExceptionCaught",
      active: true,
      severity: "Error",
    },
    {
      set: "exceptions",
      id: "TooGenericExceptionThrown",
      active: true,
      severity: "Error",
    },
    {
      set: "naming",
      id: "BooleanPropertyNaming",
      active: false,
      severity: "Error",
    },
    {
      set: "naming",
      id: "ClassNaming",
      active: true,
      severity: "Error",
    },
    {
      set: "naming",
      id: "ConstructorParameterNaming",
      active: true,
      severity: "Error",
    },
    {
      set: "naming",
      id: "EnumNaming",
      active: true,
      severity: "Error",
    },
    {
      set: "naming",
      id: "ForbiddenClassName",
      active: false,
      severity: "Error",
    },
    {
      set: "naming",
      id: "FunctionNameMaxLength",
      active: false,
      severity: "Error",
    },
    {
      set: "naming",
      id: "FunctionNameMinLength",
      active: false,
      severity: "Error",
    },
    {
      set: "naming",
      id: "FunctionNaming",
      active: true,
      severity: "Error",
    },
    {
      set: "naming",
      id: "FunctionParameterNaming",
      active: true,
      severity: "Error",
    },
    {
      set: "naming",
      id: "InvalidPackageDeclaration",
      active: true,
      severity: "Error",
    },
    {
      set: "naming",
      id: "LambdaParameterNaming",
      active: false,
      severity: "Error",
    },
    {
      set: "naming",
      id: "MatchingDeclarationName",
      active: true,
      severity: "Error",
    },
    {
      set: "naming",
      id: "MemberNameEqualsClassName",
      active: false,
      severity: "Error",
    },
    {
      set: "naming",
      id: "NoNameShadowing",
      active: false,
      severity: "Error",
    },
    {
      set: "naming",
      id: "NonBooleanPropertyPrefixedWithIs",
      active: false,
      severity: "Error",
    },
    {
      set: "naming",
      id: "ObjectPropertyNaming",
      active: true,
      severity: "Error",
    },
    {
      set: "naming",
      id: "PackageNaming",
      active: true,
      severity: "Error",
    },
    {
      set: "naming",
      id: "TopLevelPropertyNaming",
      active: true,
      severity: "Error",
    },
    {
      set: "naming",
      id: "VariableMaxLength",
      active: false,
      severity: "Error",
    },
    {
      set: "naming",
      id: "VariableMinLength",
      active: false,
      severity: "Error",
    },
    {
      set: "naming",
      id: "VariableNaming",
      active: true,
      severity: "Error",
    },
    {
      set: "performance",
      id: "ArrayPrimitive",
      active: false,
      severity: "Error",
    },
    {
      set: "performance",
      id: "CouldBeSequence",
      active: false,
      severity: "Error",
    },
    {
      set: "performance",
      id: "ForEachOnRange",
      active: true,
      severity: "Error",
    },
    {
      set: "performance",
      id: "SpreadOperator",
      active: false,
      severity: "Error",
    },
    {
      set: "performance",
      id: "UnnecessaryInitOnArray",
      active: false,
      severity: "Error",
    },
    {
      set: "performance",
      id: "UnnecessaryPartOfBinaryExpression",
      active: false,
      severity: "Error",
    },
    {
      set: "performance",
      id: "UnnecessaryTemporaryInstantiation",
      active: true,
      severity: "Error",
    },
    {
      set: "performance",
      id: "UnnecessaryTypeCasting",
      active: false,
      severity: "Error",
    },
    {
      set: "style",
      id: "AbstractClassCanBeConcreteClass",
      active: false,
      severity: "Error",
    },
    {
      set: "style",
      id: "AbstractClassCanBeInterface",
      active: false,
      severity: "Error",
    },
    {
      set: "style",
      id: "AlsoCouldBeApply",
      active: false,
      severity: "Error",
    },
    {
      set: "style",
      id: "BracesOnIfStatements",
      active: false,
      severity: "Error",
    },
    {
      set: "style",
      id: "BracesOnWhenStatements",
      active: false,
      severity: "Error",
    },
    {
      set: "style",
      id: "CanBeNonNullable",
      active: false,
      severity: "Error",
    },
    {
      set: "style",
      id: "CascadingCallWrapping",
      active: false,
      severity: "Error",
    },
    {
      set: "style",
      id: "ClassOrdering",
      active: false,
      severity: "Error",
    },
    {
      set: "style",
      id: "CollapsibleIfStatements",
      active: false,
      severity: "Error",
    },
    {
      set: "style",
      id: "DataClassContainsFunctions",
      active: false,
      severity: "Error",
    },
    {
      set: "style",
      id: "DataClassShouldBeImmutable",
      active: false,
      severity: "Error",
    },
    {
      set: "style",
      id: "DestructuringDeclarationWithTooManyEntries",
      active: true,
      severity: "Error",
    },
    {
      set: "style",
      id: "DoubleNegativeExpression",
      active: false,
      severity: "Error",
    },
    {
      set: "style",
      id: "DoubleNegativeLambda",
      active: false,
      severity: "Error",
    },
    {
      set: "style",
      id: "EqualsNullCall",
      active: true,
      severity: "Error",
    },
    {
      set: "style",
      id: "EqualsOnSignatureLine",
      active: false,
      severity: "Error",
    },
    {
      set: "style",
      id: "ExplicitCollectionElementAccessMethod",
      active: false,
      severity: "Error",
    },
    {
      set: "style",
      id: "ExplicitItLambdaMultipleParameters",
      active: true,
      severity: "Error",
    },
    {
      set: "style",
      id: "ExplicitItLambdaParameter",
      active: true,
      severity: "Error",
    },
    {
      set: "style",
      id: "ExpressionBodySyntax",
      active: false,
      severity: "Error",
    },
    {
      set: "style",
      id: "ForbiddenAnnotation",
      active: false,
      severity: "Error",
    },
    {
      set: "style",
      id: "ForbiddenComment",
      active: true,
      severity: "Error",
    },
    {
      set: "style",
      id: "ForbiddenImport",
      active: false,
      severity: "Error",
    },
    {
      set: "style",
      id: "ForbiddenMethodCall",
      active: false,
      severity: "Error",
    },
    {
      set: "style",
      id: "ForbiddenNamedParam",
      active: false,
      severity: "Error",
    },
    {
      set: "style",
      id: "ForbiddenOptIn",
      active: false,
      severity: "Error",
    },
    {
      set: "style",
      id: "ForbiddenSuppress",
      active: false,
      severity: "Error",
    },
    {
      set: "style",
      id: "ForbiddenVoid",
      active: false,
      severity: "Error",
    },
    {
      set: "style",
      id: "FunctionOnlyReturningConstant",
      active: true,
      severity: "Error",
    },
    {
      set: "style",
      id: "LoopWithTooManyJumpStatements",
      active: true,
      severity: "Error",
    },
    {
      set: "style",
      id: "MagicNumber",
      active: true,
      severity: "Error",
    },
    {
      set: "style",
      id: "MandatoryBracesLoops",
      active: false,
      severity: "Error",
    },
    {
      set: "style",
      id: "MaxChainedCallsOnSameLine",
      active: false,
      severity: "Error",
    },
    {
      set: "style",
      id: "MaxLineLength",
      active: true,
      severity: "Error",
    },
    {
      set: "style",
      id: "MayBeConstant",
      active: true,
      severity: "Error",
    },
    {
      set: "style",
      id: "ModifierOrder",
      active: true,
      severity: "Error",
    },
    {
      set: "style",
      id: "MultilineLambdaItParameter",
      active: false,
      severity: "Error",
    },
    {
      set: "style",
      id: "MultilineRawStringIndentation",
      active: false,
      severity: "Error",
    },
    {
      set: "style",
      id: "NestedClassesVisibility",
      active: true,
      severity: "Error",
    },
    {
      set: "style",
      id: "NewLineAtEndOfFile",
      active: true,
      severity: "Error",
    },
    {
      set: "style",
      id: "NoTabs",
      active: false,
      severity: "Error",
    },
    {
      set: "style",
      id: "NullableBooleanCheck",
      active: false,
      severity: "Error",
    },
    {
      set: "style",
      id: "ObjectLiteralToLambda",
      active: false,
      severity: "Error",
    },
    {
      set: "style",
      id: "OptionalAbstractKeyword",
      active: true,
      severity: "Error",
    },
    {
      set: "style",
      id: "OptionalUnit",
      active: false,
      severity: "Error",
    },
    {
      set: "style",
      id: "ProtectedMemberInFinalClass",
      active: true,
      severity: "Error",
    },
    {
      set: "style",
      id: "RangeUntilInsteadOfRangeTo",
      active: false,
      severity: "Error",
    },
    {
      set: "style",
      id: "RedundantConstructorKeyword",
      active: false,
      severity: "Error",
    },
    {
      set: "style",
      id: "RedundantExplicitType",
      active: false,
      severity: "Error",
    },
    {
      set: "style",
      id: "RedundantHigherOrderMapUsage",
      active: false,
      severity: "Error",
    },
    {
      set: "style",
      id: "RedundantVisibilityModifier",
      active: false,
      severity: "Error",
    },
    {
      set: "style",
      id: "ReturnCount",
      active: true,
      severity: "Error",
    },
    {
      set: "style",
      id: "SafeCast",
      active: true,
      severity: "Error",
    },
    {
      set: "style",
      id: "SerialVersionUIDInSerializableClass",
      active: true,
      severity: "Error",
    },
    {
      set: "style",
      id: "SpacingAfterPackageAndImports",
      active: false,
      severity: "Error",
    },
    {
      set: "style",
      id: "StringShouldBeRawString",
      active: false,
      severity: "Error",
    },
    {
      set: "style",
      id: "ThrowsCount",
      active: true,
      severity: "Error",
    },
    {
      set: "style",
      id: "TrailingWhitespace",
      active: false,
      severity: "Error",
    },
    {
      set: "style",
      id: "TrimMultilineRawString",
      active: false,
      severity: "Error",
    },
    {
      set: "style",
      id: "UnderscoresInNumericLiterals",
      active: false,
      severity: "Error",
    },
    {
      set: "style",
      id: "UnnecessaryAny",
      active: false,
      severity: "Error",
    },
    {
      set: "style",
      id: "UnnecessaryApply",
      active: false,
      severity: "Error",
    },
    {
      set: "style",
      id: "UnnecessaryBackticks",
      active: false,
      severity: "Error",
    },
    {
      set: "style",
      id: "UnnecessaryBracesAroundTrailingLambda",
      active: false,
      severity: "Error",
    },
    {
      set: "style",
      id: "UnnecessaryFilter",
      active: false,
      severity: "Error",
    },
    {
      set: "style",
      id: "UnnecessaryFullyQualifiedName",
      active: false,
      severity: "Error",
    },
    {
      set: "style",
      id: "UnnecessaryInheritance",
      active: true,
      severity: "Error",
    },
    {
      set: "style",
      id: "UnnecessaryInnerClass",
      active: false,
      severity: "Error",
    },
    {
      set: "style",
      id: "UnnecessaryLet",
      active: false,
      severity: "Error",
    },
    {
      set: "style",
      id: "UnnecessaryParentheses",
      active: false,
      severity: "Error",
    },
    {
      set: "style",
      id: "UnnecessaryReversed",
      active: false,
      severity: "Error",
    },
    {
      set: "style",
      id: "UnusedImport",
      active: false,
      severity: "Error",
    },
    {
      set: "style",
      id: "UnusedParameter",
      active: true,
      severity: "Error",
    },
    {
      set: "style",
      id: "UnusedPrivateClass",
      active: true,
      severity: "Error",
    },
    {
      set: "style",
      id: "UnusedPrivateFunction",
      active: false,
      severity: "Error",
    },
    {
      set: "style",
      id: "UnusedPrivateProperty",
      active: false,
      severity: "Error",
    },
    {
      set: "style",
      id: "UnusedVariable",
      active: false,
      severity: "Error",
    },
    {
      set: "style",
      id: "UseAnyOrNoneInsteadOfFind",
      active: false,
      severity: "Error",
    },
    {
      set: "style",
      id: "UseArrayLiteralsInAnnotations",
      active: true,
      severity: "Error",
    },
    {
      set: "style",
      id: "UseCheckNotNull",
      active: false,
      severity: "Error",
    },
    {
      set: "style",
      id: "UseCheckOrError",
      active: false,
      severity: "Error",
    },
    {
      set: "style",
      id: "UseDataClass",
      active: false,
      severity: "Error",
    },
    {
      set: "style",
      id: "UseEmptyCounterpart",
      active: false,
      severity: "Error",
    },
    {
      set: "style",
      id: "UseIfEmptyOrIfBlank",
      active: false,
      severity: "Error",
    },
    {
      set: "style",
      id: "UseIfInsteadOfWhen",
      active: false,
      severity: "Error",
    },
    {
      set: "style",
      id: "UseIsNullOrEmpty",
      active: false,
      severity: "Error",
    },
    {
      set: "style",
      id: "UseLet",
      active: false,
      severity: "Error",
    },
    {
      set: "style",
      id: "UseOrEmpty",
      active: false,
      severity: "Error",
    },
    {
      set: "style",
      id: "UseRequire",
      active: false,
      severity: "Error",
    },
    {
      set: "style",
      id: "UseRequireNotNull",
      active: false,
      severity: "Error",
    },
    {
      set: "style",
      id: "UseSumOfInsteadOfFlatMapSize",
      active: false,
      severity: "Error",
    },
    {
      set: "style",
      id: "UselessCallOnNotNull",
      active: false,
      severity: "Error",
    },
    {
      set: "style",
      id: "UtilityClassWithPublicConstructor",
      active: true,
      severity: "Error",
    },
    {
      set: "style",
      id: "VarCouldBeVal",
      active: false,
      severity: "Error",
    },
    {
      set: "style",
      id: "WildcardImport",
      active: true,
      severity: "Error",
    },
  ],
} as const;
